export const GET_ALL_SKILL_REQUEST = 'GET_ALL_SKILL_REQUEST';
export const GET_ALL_SKILL_SUCCESS = 'GET_ALL_SKILL_SUCCESS';
export const GET_ALL_SKILL_FAIL = 'GET_ALL_SKILL_FAIL';
export const GET_ALL_SKILL_RESET = 'GET_ALL_SKILL_RESET';