export const GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_REQUEST =
  "GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_REQUEST";
export const GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_SUCCESS =
  "GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_SUCCESS";
export const GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_FAIL =
  "GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_FAIL";
export const GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_RESET =
  "GET_ALL_TEACHER_FAC_SUB_INITIAL_DATA_RESET";

export const GET_ALL_TEACHER_FAC_SUB_LIST_DATA_REQUEST =
  "GET_ALL_TEACHER_FAC_SUB_LIST_DATA_REQUEST";
export const GET_ALL_TEACHER_FAC_SUB_LIST_DATA_SUCCESS =
  "GET_ALL_TEACHER_FAC_SUB_LIST_DATA_SUCCESS";
export const GET_ALL_TEACHER_FAC_SUB_LIST_DATA_FAIL =
  "GET_ALL_TEACHER_FAC_SUB_LIST_DATA_FAIL";
export const GET_ALL_TEACHER_FAC_SUB_LIST_DATA_RESET =
  "GET_ALL_TEACHER_FAC_SUB_LIST_DATA_RESET";

export const GET_SINGLE_TEACHER_FAC_SUB_DATA_REQUEST =
  "GET_SINGLE_TEACHER_FAC_SUB_DATA_REQUEST";
export const GET_SINGLE_TEACHER_FAC_SUB_DATA_SUCCESS =
  "GET_SINGLE_TEACHER_FAC_SUB_DATA_SUCCESS";
export const GET_SINGLE_TEACHER_FAC_SUB_DATA_FAIL =
  "GET_SINGLE_TEACHER_FAC_SUB_DATA_FAIL";
export const GET_SINGLE_TEACHER_FAC_SUB_DATA_RESET =
  "GET_SINGLE_TEACHER_FAC_SUB_DATA_RESET";

export const SINGLE_TEACHER_FAC_SUB_EDIT_REQUEST =
  "SINGLE_TEACHER_FAC_SUB_EDIT_REQUEST";
export const SINGLE_TEACHER_FAC_SUB_EDIT_SUCCESS =
  "SINGLE_TEACHER_FAC_SUB_EDIT_SUCCESS";
export const SINGLE_TEACHER_FAC_SUB_EDIT_FAIL =
  "SINGLE_TEACHER_FAC_SUB_EDIT_FAIL";
export const SINGLE_TEACHER_FAC_SUB_EDIT_RESET =
  "SINGLE_TEACHER_FAC_SUB_EDIT_RESET";

export const CREATE_TEACHER_FAC_SUB_INITIAL_DATA_REQUEST =
  "CREATE_TEACHER_FAC_SUB_INITIAL_DATA_REQUEST";
export const CREATE_TEACHER_FAC_SUB_INITIAL_DATA_SUCCESS =
  "CREATE_TEACHER_FAC_SUB_INITIAL_DATA_SUCCESS";
export const CREATE_TEACHER_FAC_SUB_INITIAL_DATA_FAIL =
  "CREATE_TEACHER_FAC_SUB_INITIAL_DATA_FAIL";
export const CREATE_TEACHER_FAC_SUB_INITIAL_DATA_RESET =
  "CREATE_TEACHER_FAC_SUB_INITIAL_DATA_RESET";

export const CREATE_SINGLE_TEACHER_FAC_SUB_REQUEST =
  "CREATE_SINGLE_TEACHER_FAC_SUB_REQUEST";
export const CREATE_SINGLE_TEACHER_FAC_SUB_SUCCESS =
  "CREATE_SINGLE_TEACHER_FAC_SUB_SUCCESS";
export const CREATE_SINGLE_TEACHER_FAC_SUB_FAIL =
  "CREATE_SINGLE_TEACHER_FAC_SUB_FAIL";
export const CREATE_SINGLE_TEACHER_FAC_SUB_RESET =
  "CREATE_SINGLE_TEACHER_FAC_SUB_RESET";

export const DELETE_TEACHER_FAC_SUB_REQUEST = "DELETE_TEACHER_FAC_SUB_REQUEST";
export const DELETE_TEACHER_FAC_SUB_SUCCESS = "DELETE_TEACHER_FAC_SUB_SUCCESS";
export const DELETE_TEACHER_FAC_SUB_FAIL = "DELETE_TEACHER_FAC_SUB_FAIL";
export const DELETE_TEACHER_FAC_SUB_RESET = "DELETE_TEACHER_FAC_SUB_RESET";
