export const GET_ALL_ACADEMIC_PROGRAM_REQUEST =
  "GET_ALL_ACADEMIC_PROGRAM_REQUEST";
export const GET_ALL_ACADEMIC_PROGRAM_SUCCESS =
  "GET_ALL_ACADEMIC_PROGRAM_SUCCESS";
export const GET_ALL_ACADEMIC_PROGRAM_FAIL = "GET_ALL_ACADEMIC_PROGRAM_FAIL";
export const GET_ALL_ACADEMIC_PROGRAM_RESET = "GET_ALL_ACADEMIC_PROGRAM_RESET";

export const ACADEMIC_PROGRAM_CREATE_REQUEST =
  "ACADEMIC_PROGRAM_CREATE_REQUEST";
export const ACADEMIC_PROGRAM_CREATE_SUCCESS =
  "ACADEMIC_PROGRAM_CREATE_SUCCESS";
export const ACADEMIC_PROGRAM_CREATE_FAIL = "ACADEMIC_PROGRAM_CREATE_FAIL";
export const ACADEMIC_PROGRAM_CREATE_RESET = "ACADEMIC_PROGRAM_CREATE_RESET";

export const GET_ACADEMIC_PROGRAM_OPTION_REQUEST =
  "GET_ACADEMIC_PROGRAM_OPTION_REQUEST";
export const GET_ACADEMIC_PROGRAM_OPTION_SUCCESS =
  "GET_ACADEMIC_PROGRAM_OPTION_SUCCESS";
export const GET_ACADEMIC_PROGRAM_OPTION_FAIL =
  "GET_ACADEMIC_PROGRAM_OPTION_FAIL";
export const GET_ACADEMIC_PROGRAM_OPTION_RESET =
  "GET_ACADEMIC_PROGRAM_OPTION_RESET";

export const GET_SINGLE_ACADEMIC_PROGRAM_REQUEST =
  "GET_SINGLE_ACADEMIC_PROGRAM_REQUEST";
export const GET_SINGLE_ACADEMIC_PROGRAM_SUCCESS =
  "GET_SINGLE_ACADEMIC_PROGRAM_SUCCESS";
export const GET_SINGLE_ACADEMIC_PROGRAM_FAIL =
  "GET_SINGLE_ACADEMIC_PROGRAM_FAIL";
export const GET_SINGLE_ACADEMIC_PROGRAM_RESET =
  "GET_SINGLE_ACADEMIC_PROGRAM_RESET";

export const UPDATE_SINGLE_ACADEMIC_PROGRAM_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_PROGRAM_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_PROGRAM_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_PROGRAM_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_PROGRAM_FAIL =
  "UPDATE_SINGLE_ACADEMIC_PROGRAM_FAIL";
export const UPDATE_SINGLE_ACADEMIC_PROGRAM_RESET =
  "UPDATE_SINGLE_ACADEMIC_PROGRAM_RESET";
