export const GET_ALL_ACADEMIC_CLASS_REQUEST = "GET_ALL_ACADEMIC_CLASS_REQUEST";
export const GET_ALL_ACADEMIC_CLASS_SUCCESS = "GET_ALL_ACADEMIC_CLASS_SUCCESS";
export const GET_ALL_ACADEMIC_CLASS_FAIL = "GET_ALL_ACADEMIC_CLASS_FAIL";
