export const GET_ALL_ACADEMIC_CLASS_REQUEST = "GET_ALL_ACADEMIC_CLASS_REQUEST";
export const GET_ALL_ACADEMIC_CLASS_SUCCESS = "GET_ALL_ACADEMIC_CLASS_SUCCESS";
export const GET_ALL_ACADEMIC_CLASS_FAIL = "GET_ALL_ACADEMIC_CLASS_FAIL";
export const GET_ALL_ACADEMIC_CLASS_RESET = "GET_ALL_ACADEMIC_CLASS_RESET";

export const ACADEMIC_CLASS_CREATE_REQUEST = "ACADEMIC_CLASS_CREATE_REQUEST";
export const ACADEMIC_CLASS_CREATE_SUCCESS = "ACADEMIC_CLASS_CREATE_SUCCESS";
export const ACADEMIC_CLASS_CREATE_FAIL = "ACADEMIC_CLASS_CREATE_FAIL";
export const ACADEMIC_CLASS_CREATE_RESET = "ACADEMIC_CLASS_CREATE_RESET";

export const GET_SINGLE_ACADEMIC_CLASS_REQUEST =
  "GET_SINGLE_ACADEMIC_CLASS_REQUEST";
export const GET_SINGLE_ACADEMIC_CLASS_SUCCESS =
  "GET_SINGLE_ACADEMIC_CLASS_SUCCESS";
export const GET_SINGLE_ACADEMIC_CLASS_FAIL = "GET_SINGLE_ACADEMIC_CLASS_FAIL";
export const GET_SINGLE_ACADEMIC_CLASS_RESET =
  "GET_SINGLE_ACADEMIC_CLASS_RESET";

export const UPDATE_SINGLE_ACADEMIC_CLASS_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_CLASS_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_CLASS_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_CLASS_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_CLASS_FAIL =
  "UPDATE_SINGLE_ACADEMIC_CLASS_FAIL";
export const UPDATE_SINGLE_ACADEMIC_CLASS_RESET =
  "UPDATE_SINGLE_ACADEMIC_CLASS_RESET";
