export const GET_ALL_HOBBY_REQUEST = 'GET_ALL_HOBBY_REQUEST';
export const GET_ALL_HOBBY_SUCCESS = 'GET_ALL_HOBBY_SUCCESS';
export const GET_ALL_HOBBY_FAIL = 'GET_ALL_HOBBY_FAIL';
export const GET_ALL_HOBBY_RESET = 'GET_ALL_HOBBY_RESET';