export const GET_ALL_STUDENT_PROFILE_REQUEST =
  "GET_ALL_STUDENT_PROFILE_REQUEST";
export const GET_ALL_STUDENT_PROFILE_SUCCESS =
  "GET_ALL_STUDENT_PROFILE_SUCCESS";
export const GET_ALL_STUDENT_PROFILE_FAIL = "GET_ALL_STUDENT_PROFILE_FAIL";
export const GET_ALL_STUDENT_PROFILE_RESET = "GET_ALL_STUDENT_PROFILE_RESET";

export const GET_LIST_STUDENT_PROFILE_REQUEST =
  "GET_LIST_STUDENT_PROFILE_REQUEST";
export const GET_LIST_STUDENT_PROFILE_SUCCESS =
  "GET_LIST_STUDENT_PROFILE_SUCCESS";
export const GET_LIST_STUDENT_PROFILE_FAIL = "GET_LIST_STUDENT_PROFILE_FAIL";
export const GET_LIST_STUDENT_PROFILE_RESET = "GET_LIST_STUDENT_PROFILE_RESET";

export const SINGLE_STUDENT_PROFILE_DETAILS_REQUEST =
  "SINGLE_STUDENT_PROFILE_DETAILS_REQUEST";
export const SINGLE_STUDENT_PROFILE_DETAILS_SUCCESS =
  "SINGLE_STUDENT_PROFILE_DETAILS_SUCCESS";
export const SINGLE_STUDENT_PROFILE_DETAILS_FAIL =
  "SINGLE_STUDENT_PROFILE_DETAILS_FAIL";
export const SINGLE_STUDENT_PROFILE_DETAILS_RESET =
  "SINGLE_STUDENT_PROFILE_DETAILS_RESET";

export const GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_REQUEST =
  "GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_REQUEST";
export const GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_SUCCESS =
  "GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_SUCCESS";
export const GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_FAIL =
  "GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_FAIL";
export const GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_RESET =
  "GET_SINGLE_STUDENT_PROFILE_PASSWORDRESET_DATA_RESET";

export const RESET_SINGLE_STUDENT_PROFILE_PASSWORD_REQUEST =
  "RESET_SINGLE_STUDENT_PROFILE_PASSWORD_REQUEST";
export const RESET_SINGLE_STUDENT_PROFILE_PASSWORD_SUCCESS =
  "RESET_SINGLE_STUDENT_PROFILE_PASSWORD_SUCCESS";
export const RESET_SINGLE_STUDENT_PROFILE_PASSWORD_FAIL =
  "RESET_SINGLE_STUDENT_PROFILE_PASSWORD_FAIL";
export const RESET_SINGLE_STUDENT_PROFILE_PASSWORD_RESET =
  "RESET_SINGLE_STUDENT_PROFILE_PASSWORD_RESET";

export const GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_REQUEST =
  "GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_REQUEST";
export const GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_SUCCESS =
  "GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_SUCCESS";
export const GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_FAIL =
  "GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_FAIL";
export const GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_RESET =
  "GET_SINGLE_STUDENT_PROFILE_EDIT_DATA_RESET";

export const UPDATE_SINGLE_STUDENT_PROFILE_REQUEST =
  "UPDATE_SINGLE_STUDENT_PROFILE_REQUEST";
export const UPDATE_SINGLE_STUDENT_PROFILE_SUCCESS =
  "UPDATE_SINGLE_STUDENT_PROFILE_SUCCESS";
export const UPDATE_SINGLE_STUDENT_PROFILE_FAIL =
  "UPDATE_SINGLE_STUDENT_PROFILE_FAIL";
export const UPDATE_SINGLE_STUDENT_PROFILE_RESET =
  "UPDATE_SINGLE_STUDENT_PROFILE_RESET";
