export const GET_ALL_STUDENT_PROFILE_REQUEST="GET_ALL_STUDENT_PROFILE_REQUEST";
export const GET_ALL_STUDENT_PROFILE_SUCCESS="GET_ALL_STUDENT_PROFILE_SUCCESS";
export const GET_ALL_STUDENT_PROFILE_FAIL="GET_ALL_STUDENT_PROFILE_FAIL";

export const GET_ALL_STUDENT_PROFILE_CREATE_REQUEST="GET_ALL_STUDENT_PROFILE_CREATE_REQUEST";
export const GET_ALL_STUDENT_PROFILE_CREATE_SUCCESS="GET_ALL_STUDENT_PROFILE_CREATE_SUCCESS";
export const GET_ALL_STUDENT_PROFILE_CREATE_FAIL="GET_ALL_STUDENT_PROFILE_CREATE_FAIL";


