export const GET_ALL_JOBHISTORY_REQUEST = 'GET_ALL_JOBHISTORY_REQUEST';
export const GET_ALL_JOBHISTORY_SUCCESS = 'GET_ALL_JOBHISTORY_SUCCESS';
export const GET_ALL_JOBHISTORY_FAIL = 'GET_ALL_JOBHISTORY_FAIL';
export const GET_ALL_JOBHISTORY_RESET = 'GET_ALL_JOBHISTORY_RESET';