export const GET_ALL_GUARDIAN_REQUEST = 'GET_ALL_GUARDIAN_REQUEST';
export const GET_ALL_GUARDIAN_SUCCESS = 'GET_ALL_GUARDIAN_SUCCESS';
export const GET_ALL_GUARDIAN_FAIL = 'GET_ALL_GUARDIAN_FAIL';
export const GET_ALL_GUARDIAN_RESET = 'GET_ALL_GUARDIAN_RESET';

export const GET_SINGLE_GUARDIAN_REQUEST = 'GET_SINGLE_GUARDIAN_REQUEST';
export const GET_SINGLE_GUARDIAN_SUCCESS = 'GET_SINGLE_GUARDIAN_SUCCESS';
export const GET_SINGLE_GUARDIAN_FAIL = 'GET_SINGLE_GUARDIAN_FAIL';
export const GET_SINGLE_GUARDIAN_RESET = 'GET_SINGLE_GUARDIAN_RESET';