export const GET_ALL_HR_VALUE_REQUEST = "GET_ALL_HR_VALUE_REQUEST";
export const GET_ALL_HR_VALUE_SUCCESS = "GET_ALL_HR_VALUE_SUCCESS";
export const GET_ALL_HR_VALUE_FAIL = "GET_ALL_HR_VALUE_FAIL";
export const GET_ALL_HR_VALUE_RESET = "GET_ALL_HR_VALUE_RESET";

export const GET_LIST_HR_VALUE_REQUEST = "GET_LIST_HR_VALUE_REQUEST";
export const GET_LIST_HR_VALUE_SUCCESS = "GET_LIST_HR_VALUE_SUCCESS";
export const GET_LIST_HR_VALUE_FAIL = "GET_LIST_HR_VALUE_FAIL";
export const GET_LIST_HR_VALUE_RESET = "GET_LIST_HR_VALUE_RESET";

export const GET_SINGLE_TO_CREATE_HR_VALUE_REQUEST = "GET_SINGLE_TO_CREATE_HR_VALUE_REQUEST";
export const GET_SINGLE_TO_CREATE_HR_VALUE_SUCCESS = "GET_SINGLE_TO_CREATE_HR_VALUE_SUCCESS";
export const GET_SINGLE_TO_CREATE_HR_VALUE_FAIL = "GET_SINGLE_TO_CREATE_HR_VALUE_FAIL";
export const GET_SINGLE_TO_CREATE_HR_VALUE_RESET = "GET_SINGLE_TO_CREATE_HR_VALUE_RESET";

export const GET_SINGLE_TO_EDIT_HR_VALUE_REQUEST = "GET_SINGLE_TO_EDIT_HR_VALUE_REQUEST";
export const GET_SINGLE_TO_EDIT_HR_VALUE_SUCCESS = "GET_SINGLE_TO_EDIT_HR_VALUE_SUCCESS";
export const GET_SINGLE_TO_EDIT_HR_VALUE_FAIL = "GET_SINGLE_TO_EDIT_HR_VALUE_FAIL";
export const GET_SINGLE_TO_EDIT_HR_VALUE_RESET = "GET_SINGLE_TO_EDIT_HR_VALUE_RESET";

export const POST_HR_VALUE_REQUEST = "POST_HR_VALUE_REQUEST";
export const POST_HR_VALUE_SUCCESS = "POST_HR_VALUE_SUCCESS";
export const POST_HR_VALUE_FAIL = "POST_HR_VALUE_FAIL";
export const POST_HR_VALUE_RESET = "POST_HR_VALUE_RESET";

export const PUT_HR_VALUE_REQUEST = "PUT_HR_VALUE_REQUEST";
export const PUT_HR_VALUE_SUCCESS = "PUT_HR_VALUE_SUCCESS";
export const PUT_HR_VALUE_FAIL = "PUT_HR_VALUE_FAIL";
export const PUT_HR_VALUE_RESET = "PUT_HR_VALUE_RESET";

export const POST_FILE_UPLOAD_HEADER_BANNER_REQUEST = "POST_FILE_UPLOAD_HEADER_BANNER_REQUEST";
export const POST_FILE_UPLOAD_HEADER_BANNER_SUCCESS = "POST_FILE_UPLOAD_HEADER_BANNER_SUCCESS";
export const POST_FILE_UPLOAD_HEADER_BANNER_FAIL = "POST_FILE_UPLOAD_HEADER_BANNER_FAIL";
export const POST_FILE_UPLOAD_HEADER_BANNER_RESET = "POST_FILE_UPLOAD_HEADER_BANNER_RESET";

export const POST_FILE_UPLOAD_SCHOOL_LOGO_REQUEST = "POST_FILE_UPLOAD_SCHOOL_LOGO_REQUEST";
export const POST_FILE_UPLOAD_SCHOOL_LOGO_SUCCESS = "POST_FILE_UPLOAD_SCHOOL_LOGO_SUCCESS";
export const POST_FILE_UPLOAD_SCHOOL_LOGO_FAIL = "POST_FILE_UPLOAD_SCHOOL_LOGO_FAIL";
export const POST_FILE_UPLOAD_SCHOOL_LOGO_RESET = "POST_FILE_UPLOAD_SCHOOL_LOGO_RESET";

export const POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_REQUEST = "POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_REQUEST";
export const POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_SUCCESS = "POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_SUCCESS";
export const POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_FAIL = "POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_FAIL";
export const POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_RESET = "POST_FILE_UPLOAD_PRINCIPLE_SIGNATURE_RESET";


