export const GET_ALL_CLASS_SUBJECT_REQUEST = "GET_ALL_CLASS_SUBJECT_REQUEST";
export const GET_ALL_CLASS_SUBJECT_SUCCESS = "GET_ALL_CLASS_SUBJECT_SUCCESS";
export const GET_ALL_CLASS_SUBJECT_FAIL = "GET_ALL_CLASS_SUBJECT_FAIL";
export const GET_ALL_CLASS_SUBJECT_RESET = "GET_ALL_CLASS_SUBJECT_RESET";

export const GET_CLASS_SUBJECT_LIST_REQUEST = "GET_CLASS_SUBJECT_LIST_REQUEST";
export const GET_CLASS_SUBJECT_LIST_SUCCESS = "GET_CLASS_SUBJECT_LIST_SUCCESS";
export const GET_CLASS_SUBJECT_LIST_FAIL = "GET_CLASS_SUBJECT_LIST_FAIL";
export const GET_CLASS_SUBJECT_LIST_RESET = "GET_CLASS_SUBJECT_LIST_RESET";

export const GET_SINGLE_CLASS_SUBJECT_REQUEST =
  "GET_SINGLE_CLASS_SUBJECT_REQUEST";
export const GET_SINGLE_CLASS_SUBJECT_SUCCESS =
  "GET_SINGLE_CLASS_SUBJECT_SUCCESS";
export const GET_SINGLE_CLASS_SUBJECT_FAIL = "GET_SINGLE_CLASS_SUBJECT_FAIL";
export const GET_SINGLE_CLASS_SUBJECT_RESET = "GET_SINGLE_CLASS_SUBJECT_RESET";

export const UPDATE_SINGLE_CLASS_SUBJECT_REQUEST =
  "UPDATE_SINGLE_CLASS_SUBJECT_REQUEST";
export const UPDATE_SINGLE_CLASS_SUBJECT_SUCCESS =
  "UPDATE_SINGLE_CLASS_SUBJECT_SUCCESS";
export const UPDATE_SINGLE_CLASS_SUBJECT_FAIL =
  "UPDATE_SINGLE_CLASS_SUBJECT_FAIL";
export const UPDATE_SINGLE_CLASS_SUBJECT_RESET =
  "UPDATE_SINGLE_CLASS_SUBJECT_RESET";

export const GET_TO_CREATE_CLASS_SUBJECT_REQUEST =
  "GET_TO_CREATE_CLASS_SUBJECT_REQUEST";
export const GET_TO_CREATE_CLASS_SUBJECT_SUCCESS =
  "GET_TO_CREATE_CLASS_SUBJECT_SUCCESS";
export const GET_TO_CREATE_CLASS_SUBJECT_FAIL =
  "GET_TO_CREATE_CLASS_SUBJECT_FAIL";
export const GET_TO_CREATE_CLASS_SUBJECT_RESET =
  "GET_TO_CREATE_CLASS_SUBJECT_RESET";

export const POST_TO_CREATE_CLASS_SUBJECT_REQUEST =
  "POST_TO_CREATE_CLASS_SUBJECT_REQUEST";
export const POST_TO_CREATE_CLASS_SUBJECT_SUCCESS =
  "POST_TO_CREATE_CLASS_SUBJECT_SUCCESS";
export const POST_TO_CREATE_CLASS_SUBJECT_FAIL =
  "POST_TO_CREATE_CLASS_SUBJECT_FAIL";
export const POST_TO_CREATE_CLASS_SUBJECT_RESET =
  "POST_TO_CREATE_CLASS_SUBJECT_RESET";

  export const DELETE_CLASS_SUBJECT_REQUEST =
  "DELETE_CLASS_SUBJECT_REQUEST";
export const DELETE_CLASS_SUBJECT_SUCCESS =
  "DELETE_CLASS_SUBJECT_SUCCESS";
export const DELETE_CLASS_SUBJECT_FAIL =
  "DELETE_CLASS_SUBJECT_FAIL";
export const DELETE_CLASS_SUBJECT_RESET =
  "DELETE_CLASS_SUBJECT_RESET";
