export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_REQUEST =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_REQUEST";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_SUCCESS =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_SUCCESS";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_FAIL =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_FAIL";
export const GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_RESET =
  "GET_ALL_EXAM_SCHEDULE_INITIAL_DATA_RESET";

export const GET_EVENT_FOR_EXAM_SCHEDULE_REQUEST =
  "GET_EVENT_FOR_EXAM_SCHEDULE_REQUEST";
export const GET_EVENT_FOR_EXAM_SCHEDULE_SUCCESS =
  "GET_EVENT_FOR_EXAM_SCHEDULE_SUCCESS";
export const GET_EVENT_FOR_EXAM_SCHEDULE_FAIL =
  "GET_EVENT_FOR_EXAM_SCHEDULE_FAIL";
export const GET_EVENT_FOR_EXAM_SCHEDULE_RESET =
  "GET_EVENT_FOR_EXAM_SCHEDULE_RESET";

export const GET_EXAM_SCHEDULE_LIST_REQUEST = "GET_EXAM_SCHEDULE_LIST_REQUEST";
export const GET_EXAM_SCHEDULE_LIST_SUCCESS = "GET_EXAM_SCHEDULE_LIST_SUCCESS";
export const GET_EXAM_SCHEDULE_LIST_FAIL = "GET_EXAM_SCHEDULE_LIST_FAIL";
export const GET_EXAM_SCHEDULE_LIST_RESET = "GET_EXAM_SCHEDULE_LIST_RESET";

export const GET_SINGLE_EXAM_SCHEDULE_CREATE_REQUEST =
  "GET_SINGLE_EXAM_SCHEDULE_CREATE_REQUEST";
export const GET_SINGLE_EXAM_SCHEDULE_CREATE_SUCCESS =
  "GET_SINGLE_EXAM_SCHEDULE_CREATE_SUCCESS";
export const GET_SINGLE_EXAM_SCHEDULE_CREATE_FAIL =
  "GET_SINGLE_EXAM_SCHEDULE_CREATE_FAIL";
export const GET_SINGLE_EXAM_SCHEDULE_CREATE_RESET =
  "GET_SINGLE_EXAM_SCHEDULE_CREATE_RESET";

export const POST_SINGLE_EXAM_SCHEDULE_CREATE_REQUEST =
  "POST_SINGLE_EXAM_SCHEDULE_CREATE_REQUEST";
export const POST_SINGLE_EXAM_SCHEDULE_CREATE_SUCCESS =
  "POST_SINGLE_EXAM_SCHEDULE_CREATE_SUCCESS";
export const POST_SINGLE_EXAM_SCHEDULE_CREATE_FAIL =
  "POST_SINGLE_EXAM_SCHEDULE_CREATE_FAIL";
export const POST_SINGLE_EXAM_SCHEDULE_CREATE_RESET =
  "POST_SINGLE_EXAM_SCHEDULE_CREATE_RESET";

export const GET_SINGLE_EXAM_SCHEDULE_EDIT_REQUEST =
  "GET_SINGLE_EXAM_SCHEDULE_EDIT_REQUEST";
export const GET_SINGLE_EXAM_SCHEDULE_EDIT_SUCCESS =
  "GET_SINGLE_EXAM_SCHEDULE_EDIT_SUCCESS";
export const GET_SINGLE_EXAM_SCHEDULE_EDIT_FAIL =
  "GET_SINGLE_EXAM_SCHEDULE_EDIT_FAIL";
export const GET_SINGLE_EXAM_SCHEDULE_EDIT_RESET =
  "GET_SINGLE_EXAM_SCHEDULE_EDIT_RESET";

export const SINGLE_EXAM_SCHEDULE_EDIT_REQUEST =
  "SINGLE_EXAM_SCHEDULE_EDIT_REQUEST";
export const SINGLE_EXAM_SCHEDULE_EDIT_SUCCESS =
  "SINGLE_EXAM_SCHEDULE_EDIT_SUCCESS";
export const SINGLE_EXAM_SCHEDULE_EDIT_FAIL = "SINGLE_EXAM_SCHEDULE_EDIT_FAIL";
export const SINGLE_EXAM_SCHEDULE_EDIT_RESET =
  "SINGLE_EXAM_SCHEDULE_EDIT_RESET";

export const DELETE_EXAM_SCHEDULE_REQUEST = "DELETE_EXAM_SCHEDULE_REQUEST";
export const DELETE_EXAM_SCHEDULE_SUCCESS = "DELETE_EXAM_SCHEDULE_SUCCESS";
export const DELETE_EXAM_SCHEDULE_FAIL = "DELETE_EXAM_SCHEDULE_FAIL";
export const DELETE_EXAM_SCHEDULE_RESET = "DELETE_EXAM_SCHEDULE_RESET";

export const GET_GENERATE_EXAM_SCHEDULE_REQUEST = "GET_GENERATE_EXAM_SCHEDULE_REQUEST";
export const GET_GENERATE_EXAM_SCHEDULE_SUCCESS = "GET_GENERATE_EXAM_SCHEDULE_SUCCESS";
export const GET_GENERATE_EXAM_SCHEDULE_FAIL = "GET_GENERATE_EXAM_SCHEDULE_FAIL";
export const GET_GENERATE_EXAM_SCHEDULE_RESET = "GET_GENERATE_EXAM_SCHEDULE_RESET";

export const POST_GENERATE_EXAM_SCHEDULE_REQUEST = "POST_GENERATE_EXAM_SCHEDULE_REQUEST";
export const POST_GENERATE_EXAM_SCHEDULE_SUCCESS = "POST_GENERATE_EXAM_SCHEDULE_SUCCESS";
export const POST_GENERATE_EXAM_SCHEDULE_FAIL = "POST_GENERATE_EXAM_SCHEDULE_FAIL";
export const POST_GENERATE_EXAM_SCHEDULE_RESET = "POST_GENERATE_EXAM_SCHEDULE_RESET";
