export const GET_ALL_ASSIGN_ECA_REQUEST = "GET_ALL_ASSIGN_ECA_REQUEST";
export const GET_ALL_ASSIGN_ECA_SUCCESS = "GET_ALL_ASSIGN_ECA_SUCCESS";
export const GET_ALL_ASSIGN_ECA_FAIL = "GET_ALL_ASSIGN_ECA_FAIL";
export const GET_ALL_ASSIGN_ECA_RESET = "GET_ALL_ASSIGN_ECA_RESET";

export const GET_LIST_ASSIGN_ECA_REQUEST = "GET_LIST_ASSIGN_ECA_REQUEST";
export const GET_LIST_ASSIGN_ECA_SUCCESS = "GET_LIST_ASSIGN_ECA_SUCCESS";
export const GET_LIST_ASSIGN_ECA_FAIL = "GET_LIST_ASSIGN_ECA_FAIL";
export const GET_LIST_ASSIGN_ECA_RESET = "GET_LIST_ASSIGN_ECA_RESET";

export const GET_SINGLE_CREATE_ASSIGN_ECA_REQUEST = "GET_SINGLE_CREATE_ASSIGN_ECA_REQUEST";
export const GET_SINGLE_CREATE_ASSIGN_ECA_SUCCESS = "GET_SINGLE_CREATE_ASSIGN_ECA_SUCCESS";
export const GET_SINGLE_CREATE_ASSIGN_ECA_FAIL = "GET_SINGLE_CREATE_ASSIGN_ECA_FAIL";
export const GET_SINGLE_CREATE_ASSIGN_ECA_RESET = "GET_SINGLE_CREATE_ASSIGN_ECA_RESET";

export const POST_ASSIGN_ECA_REQUEST = "POST_ASSIGN_ECA_REQUEST";
export const POST_ASSIGN_ECA_SUCCESS = "POST_ASSIGN_ECA_SUCCESS";
export const POST_ASSIGN_ECA_FAIL = "POST_ASSIGN_ECA_FAIL";
export const POST_ASSIGN_ECA_RESET = "POST_ASSIGN_ECA_RESET";