export const GET_ALL_GENERATE_PUBLISH_REQUEST =
  "GET_ALL_GENERATE_PUBLISH_REQUEST";
export const GET_ALL_GENERATE_PUBLISH_SUCCESS =
  "GET_ALL_GENERATE_PUBLISH_SUCCESS";
export const GET_ALL_GENERATE_PUBLISH_FAIL = "GET_ALL_GENERATE_PUBLISH_FAIL";
export const GET_ALL_GENERATE_PUBLISH_RESET = "GET_ALL_GENERATE_PUBLISH_RESET";

export const GET_ALL_GENERATE_REQUEST = "GET_ALL_GENERATE_REQUEST";
export const GET_ALL_GENERATE_SUCCESS = "GET_ALL_GENERATE_SUCCESS";
export const GET_ALL_GENERATE_FAIL = "GET_ALL_GENERATE_FAIL";
export const GET_ALL_GENERATE_RESET = "GET_ALL_GENERATE_RESET";

export const GET_ALL_GENERATE_PUBLISH_RESULT_REQUEST =
  "GET_ALL_GENERATE_PUBLISH_RESULT_REQUEST";
export const GET_ALL_GENERATE_PUBLISH_RESULT_SUCCESS =
  "GET_ALL_GENERATE_PUBLISH_RESULT_SUCCESS";
export const GET_ALL_GENERATE_PUBLISH_RESULT_FAIL =
  "GET_ALL_GENERATE_PUBLISH_RESULT_FAIL";
export const GET_ALL_GENERATE_PUBLISH_RESULT_RESET =
  "GET_ALL_GENERATE_PUBLISH_RESULT_RESET";
