export const GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_REQUEST =
  "GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_REQUEST";
export const GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_SUCCESS =
  "GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_SUCCESS";
export const GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_FAIL =
  "GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_FAIL";
export const GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_RESET =
  "GET_ALL_STUDEN_ATTENDANCE_INITIAL_DATA_RESET";

export const GET_ALL_STUDEN_ATTENDANCE_REQUEST =
  "GET_ALL_STUDEN_ATTENDANCE_REQUEST";
export const GET_ALL_STUDEN_ATTENDANCE_SUCCESS =
  "GET_ALL_STUDEN_ATTENDANCE_SUCCESS";
export const GET_ALL_STUDEN_ATTENDANCE_FAIL = "GET_ALL_STUDEN_ATTENDANCE_FAIL";
export const GET_ALL_STUDEN_ATTENDANCE_RESET =
  "GET_ALL_STUDEN_ATTENDANCE_RESET";

export const GET_BULK_STUDENT_ATTENDANCE_REQUEST =
  "GET_BULK_STUDENT_ATTENDANCE_REQUEST";
export const GET_BULK_STUDENT_ATTENDANCE_SUCCESS =
  "GET_BULK_STUDENT_ATTENDANCE_SUCCESS";
export const GET_BULK_STUDENT_ATTENDANCE_FAIL =
  "GET_BULK_STUDENT_ATTENDANCE_FAIL";
export const GET_BULK_STUDENT_ATTENDANCE_RESET =
  "GET_BULK_STUDENT_ATTENDANCE_RESET";

export const POST_BULK_STUDENT_ATTENDANCE_REQUEST =
  "POST_BULK_STUDENT_ATTENDANCE_REQUEST";
export const POST_BULK_STUDENT_ATTENDANCE_SUCCESS =
  "POST_BULK_STUDENT_ATTENDANCE_SUCCESS";
export const POST_BULK_STUDENT_ATTENDANCE_FAIL =
  "POST_BULK_STUDENT_ATTENDANCE_FAIL";
export const POST_BULK_STUDENT_ATTENDANCE_RESET =
  "POST_BULK_STUDENT_ATTENDANCE_RESET";

  export const GET_GENERATED_STUDENT_ATTENDANCE_REQUEST =
  "GET_GENERATED_STUDENT_ATTENDANCE_REQUEST";
export const GET_GENERATED_STUDENT_ATTENDANCE_SUCCESS =
  "GET_GENERATED_STUDENT_ATTENDANCE_SUCCESS";
export const GET_GENERATED_STUDENT_ATTENDANCE_FAIL =
  "GET_GENERATED_STUDENT_ATTENDANCE_FAIL";
export const GET_GENERATED_STUDENT_ATTENDANCE_RESET =
  "GET_GENERATED_STUDENT_ATTENDANCE_RESET";
