export const GET_ALL_ACADEMIC_YEAR_REQUEST = "GET_ALL_ACADEMIC_YEAR_REQUEST";
export const GET_ALL_ACADEMIC_YEAR_SUCCESS = "GET_ALL_ACADEMIC_YEAR_SUCCESS";
export const GET_ALL_ACADEMIC_YEAR_FAIL = "GET_ALL_ACADEMIC_YEAR_FAIL";
export const GET_ALL_ACADEMIC_YEAR_RESET = "GET_ALL_ACADEMIC_YEAR_RESET";

export const ACADEMIC_YEAR_CREATE_REQUEST = "ACADEMIC_YEAR_CREATE_REQUEST";
export const ACADEMIC_YEAR_CREATE_SUCCESS = "ACADEMIC_YEAR_CREATE_SUCCESS";
export const ACADEMIC_YEAR_CREATE_FAIL = "ACADEMIC_YEAR_CREATE_FAIL";
export const ACADEMIC_YEAR_CREATE_RESET = "ACADEMIC_YEAR_CREATE_RESET";

export const GET_ACADEMIC_YEAR_OPTION_REQUEST =
  "GET_ACADEMIC_YEAR_OPTION_REQUEST";
export const GET_ACADEMIC_YEAR_OPTION_SUCCESS =
  "GET_ACADEMIC_YEAR_OPTION_SUCCESS";
export const GET_ACADEMIC_YEAR_OPTION_FAIL = "GET_ACADEMIC_YEAR_OPTION_FAIL";
export const GET_ACADEMIC_YEAR_OPTION_RESET = "GET_ACADEMIC_YEAR_OPTION_RESET";

export const GET_SINGLE_ACADEMIC_YEAR_REQUEST =
  "GET_SINGLE_ACADEMIC_YEAR_REQUEST";
export const GET_SINGLE_ACADEMIC_YEAR_SUCCESS =
  "GET_SINGLE_ACADEMIC_YEAR_SUCCESS";
export const GET_SINGLE_ACADEMIC_YEAR_FAIL = "GET_SINGLE_ACADEMIC_YEAR_FAIL";
export const GET_SINGLE_ACADEMIC_YEAR_RESET = "GET_SINGLE_ACADEMIC_YEAR_RESET";

export const UPDATE_SINGLE_ACADEMIC_YEAR_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_YEAR_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_YEAR_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_YEAR_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_YEAR_FAIL =
  "UPDATE_SINGLE_ACADEMIC_YEAR_FAIL";
export const UPDATE_SINGLE_ACADEMIC_YEAR_RESET =
  "UPDATE_SINGLE_ACADEMIC_YEAR_RESET";

  export const GET_ACADEMIC_YEAR_CHECK_REQUEST =
  "GET_ACADEMIC_YEAR_CHECK_REQUEST";
export const GET_ACADEMIC_YEAR_CHECK_SUCCESS =
  "GET_ACADEMIC_YEAR_CHECK_SUCCESS";
export const GET_ACADEMIC_YEAR_CHECK_FAIL = "GET_ACADEMIC_YEAR_CHECK_FAIL";
export const GET_ACADEMIC_YEAR_CHECK_RESET = "GET_ACADEMIC_YEAR_CHECK_RESET";

