export const GET_ALL_ECA_LOOK_UP_REQUEST = "GET_ALL_ECA_LOOK_UP_REQUEST";
export const GET_ALL_ECA_LOOK_UP_SUCCESS = "GET_ALL_ECA_LOOK_UP_SUCCESS";
export const GET_ALL_ECA_LOOK_UP_FAIL = "GET_ALL_ECA_LOOK_UP_FAIL";
export const GET_ALL_ECA_LOOK_UP_RESET = "GET_ALL_ECA_LOOK_UP_RESET";

export const GET_LIST_ECA_LOOK_UP_REQUEST = "GET_LIST_ECA_LOOK_UP_REQUEST";
export const GET_LIST_ECA_LOOK_UP_SUCCESS = "GET_LIST_ECA_LOOK_UP_SUCCESS";
export const GET_LIST_ECA_LOOK_UP_FAIL = "GET_LIST_ECA_LOOK_UP_FAIL";
export const GET_LIST_ECA_LOOK_UP_RESET = "GET_LIST_ECA_LOOK_UP_RESET";

export const GET_SINGLE_EDIT_ECA_LOOK_UP_REQUEST = "GET_SINGLE_EDIT_ECA_LOOK_UP_REQUEST";
export const GET_SINGLE_EDIT_ECA_LOOK_UP_SUCCESS = "GET_SINGLE_EDIT_ECA_LOOK_UP_SUCCESS";
export const GET_SINGLE_EDIT_ECA_LOOK_UP_FAIL = "GET_SINGLE_EDIT_ECA_LOOK_UP_FAIL";
export const GET_SINGLE_EDIT_ECA_LOOK_UP_RESET = "GET_SINGLE_EDIT_ECA_LOOK_UP_RESET";

export const GET_SINGLE_CREATE_ECA_LOOK_UP_REQUEST = "GET_SINGLE_CREATE_ECA_LOOK_UP_REQUEST";
export const GET_SINGLE_CREATE_ECA_LOOK_UP_SUCCESS = "GET_SINGLE_CREATE_ECA_LOOK_UP_SUCCESS";
export const GET_SINGLE_CREATE_ECA_LOOK_UP_FAIL = "GET_SINGLE_CREATE_ECA_LOOK_UP_FAIL";
export const GET_SINGLE_CREATE_ECA_LOOK_UP_RESET = "GET_SINGLE_CREATE_ECA_LOOK_UP_RESET";

export const GET_DETAIL_ECA_LOOK_UP_REQUEST = "GET_DETAIL_ECA_LOOK_UP_REQUEST";
export const GET_DETAIL_ECA_LOOK_UP_SUCCESS = "GET_DETAIL_ECA_LOOK_UP_SUCCESS";
export const GET_DETAIL_ECA_LOOK_UP_FAIL = "GET_DETAIL_ECA_LOOK_UP_FAIL";
export const GET_DETAIL_ECA_LOOK_UP_RESET = "GET_DETAIL_ECA_LOOK_UP_RESET";

export const POST_ECA_LOOK_UP_REQUEST = "POST_ECA_LOOK_UP_REQUEST";
export const POST_ECA_LOOK_UP_SUCCESS = "POST_ECA_LOOK_UP_SUCCESS";
export const POST_ECA_LOOK_UP_FAIL = "POST_ECA_LOOK_UP_FAIL";
export const POST_ECA_LOOK_UP_RESET = "POST_ECA_LOOK_UP_RESET";

export const PUT_ECA_LOOK_UP_REQUEST = "PUT_ECA_LOOK_UP_REQUEST";
export const PUT_ECA_LOOK_UP_SUCCESS = "PUT_ECA_LOOK_UP_SUCCESS";
export const PUT_ECA_LOOK_UP_FAIL = "PUT_ECA_LOOK_UP_FAIL";
export const PUT_ECA_LOOK_UP_RESET = "PUT_ECA_LOOK_UP_RESET";