export const GET_ALL_FAMILYMEMBER_REQUEST = 'GET_ALL_FAMILYMEMBER_REQUEST';
export const GET_ALL_FAMILYMEMBER_SUCCESS = 'GET_ALL_FAMILYMEMBER_SUCCESS';
export const GET_ALL_FAMILYMEMBER_FAIL = 'GET_ALL_FAMILYMEMBER_FAIL';
export const GET_ALL_FAMILYMEMBER_RESET = 'GET_ALL_FAMILYMEMBER_RESET';