export const GET_ALL_OLD_QUESTIONS_REQUEST = "GET_ALL_OLD_QUESTIONS_REQUEST";
export const GET_ALL_OLD_QUESTIONS_SUCCESS = "GET_ALL_OLD_QUESTIONS_SUCCESS";
export const GET_ALL_OLD_QUESTIONS_FAIL = "GET_ALL_OLD_QUESTIONS_FAIL";
export const GET_ALL_OLD_QUESTIONS_RESET = "GET_ALL_OLD_QUESTIONS_RESET";

export const GET_LIST_OF_OLD_QUESTIONS_REQUEST =
  "GET_LIST_OF_OLD_QUESTIONS_REQUEST";
export const GET_LIST_OF_OLD_QUESTIONS_SUCCESS =
  "GET_LIST_OF_OLD_QUESTIONS_SUCCESS";
export const GET_LIST_OF_OLD_QUESTIONS_FAIL = "GET_LIST_OF_OLD_QUESTIONS_FAIL";
export const GET_LIST_OF_OLD_QUESTIONS_RESET =
  "GET_LIST_OF_OLD_QUESTIONS_RESET";

export const GET_SUBJECT_OF_OLD_QUESTIONS_REQUEST =
  "GET_SUBJECT_OF_OLD_QUESTIONS_REQUEST";
export const GET_SUBJECT_OF_OLD_QUESTIONS_SUCCESS =
  "GET_SUBJECT_OF_OLD_QUESTIONS_SUCCESS";
export const GET_SUBJECT_OF_OLD_QUESTIONS_FAIL =
  "GET_SUBJECT_OF_OLD_QUESTIONS_FAIL";
export const GET_SUBJECT_OF_OLD_QUESTIONS_RESET =
  "GET_SUBJECT_OF_OLD_QUESTIONS_RESET";

export const GET_SINGLE_TO_CREATE_OLD_QUESTIONS_REQUEST =
  "GET_SINGLE_TO_CREATE_OLD_QUESTIONS_REQUEST";
export const GET_SINGLE_TO_CREATE_OLD_QUESTIONS_SUCCESS =
  "GET_SINGLE_TO_CREATE_OLD_QUESTIONS_SUCCESS";
export const GET_SINGLE_TO_CREATE_OLD_QUESTIONS_FAIL =
  "GET_SINGLE_TO_CREATE_OLD_QUESTIONS_FAIL";
export const GET_SINGLE_TO_CREATE_OLD_QUESTIONS_RESET =
  "GET_SINGLE_TO_CREATE_OLD_QUESTIONS_RESET";

export const GET_SINGLE_TO_EDIT_OLD_QUESTIONS_REQUEST =
  "GET_SINGLE_TO_EDIT_OLD_QUESTIONS_REQUEST";
export const GET_SINGLE_TO_EDIT_OLD_QUESTIONS_SUCCESS =
  "GET_SINGLE_TO_EDIT_OLD_QUESTIONS_SUCCESS";
export const GET_SINGLE_TO_EDIT_OLD_QUESTIONS_FAIL =
  "GET_SINGLE_TO_EDIT_OLD_QUESTIONS_FAIL";
export const GET_SINGLE_TO_EDIT_OLD_QUESTIONS_RESET =
  "GET_SINGLE_TO_EDIT_OLD_QUESTIONS_RESET";

export const PUT_OLD_QUESTIONS_REQUEST = "PUT_OLD_QUESTIONS_REQUEST";
export const PUT_OLD_QUESTIONS_SUCCESS = "PUT_OLD_QUESTIONS_SUCCESS";
export const PUT_OLD_QUESTIONS_FAIL = "PUT_OLD_QUESTIONS_FAIL";
export const PUT_OLD_QUESTIONS_RESET = "PUT_OLD_QUESTIONS_RESET";

export const POST_OLD_QUESTIONS_REQUEST = "POST_OLD_QUESTIONS_REQUEST";
export const POST_OLD_QUESTIONS_SUCCESS = "POST_OLD_QUESTIONS_SUCCESS";
export const POST_OLD_QUESTIONS_FAIL = "POST_OLD_QUESTIONS_FAIL";
export const POST_OLD_QUESTIONS_RESET = "POST_OLD_QUESTIONS_RESET";

export const DOWNLOAD_OLD_QUESTIONS_REQUEST =
  "DOWNLOAD_OLD_QUESTIONS_REQUEST";
export const DOWNLOAD_OLD_QUESTIONS_SUCCESS =
  "DOWNLOAD_OLD_QUESTIONS_SUCCESS";
export const DOWNLOAD_OLD_QUESTIONS_FAIL =
  "DOWNLOAD_OLD_QUESTIONS_FAIL";
export const DOWNLOAD_OLD_QUESTIONS_RESET =
  "DOWNLOAD_OLD_QUESTIONS_RESET";
