export const GET_ALL_ECA_DATA_REQUEST = "GET_ALL_ECA_DATA_REQUEST";
export const GET_ALL_ECA_DATA_SUCCESS = "GET_ALL_ECA_DATA_SUCCESS";
export const GET_ALL_ECA_DATA_FAIL = "GET_ALL_ECA_DATA_FAIL";
export const GET_ALL_ECA_DATA_RESET = "GET_ALL_ECA_DATA_RESET";

export const GET_BULK_EDIT_ECA_DATA_REQUEST = "GET_BULK_EDIT_ECA_DATA_REQUEST";
export const GET_BULK_EDIT_ECA_DATA_SUCCESS = "GET_BULK_EDIT_ECA_DATA_SUCCESS";
export const GET_BULK_EDIT_ECA_DATA_FAIL = "GET_BULK_EDIT_ECA_DATA_FAIL";
export const GET_BULK_EDIT_ECA_DATA_RESET = "GET_BULK_EDIT_ECA_DATA_RESET";

export const GET_LIST_ECA_DATA_REQUEST = "GET_LIST_ECA_DATA_REQUEST";
export const GET_LIST_ECA_DATA_SUCCESS = "GET_LIST_ECA_DATA_SUCCESS";
export const GET_LIST_ECA_DATA_FAIL = "GET_LIST_ECA_DATA_FAIL";
export const GET_LIST_ECA_DATA_RESET = "GET_LIST_ECA_DATA_RESET";

export const POST_BULK_ECA_DATA_REQUEST =
  "POST_BULK_ECA_DATA_REQUEST";
export const POST_BULK_ECA_DATA_SUCCESS =
  "POST_BULK_ECA_DATA_SUCCESS";
export const POST_BULK_ECA_DATA_FAIL = "POST_BULK_ECA_DATA_FAIL";
export const POST_BULK_ECA_DATA_RESET =
  "POST_BULK_ECA_DATA_RESET";
