export const GET_ADMISSION_CONFIG_INITIAL_DATA_REQUEST =
  "GET_ADMISSION_CONFIG_INITIAL_DATA_REQUEST";
export const GET_ADMISSION_CONFIG_INITIAL_DATA_SUCCESS =
  "GET_ADMISSION_CONFIG_INITIAL_DATA_SUCCESS";
export const GET_ADMISSION_CONFIG_INITIAL_DATA_FAIL =
  "GET_ADMISSION_CONFIG_INITIAL_DATA_FAIL";
export const GET_ADMISSION_CONFIG_INITIAL_DATA_RESET =
  "GET_ADMISSION_CONFIG_INITIAL_DATA_RESET";

export const GET_ADMISSION_CONFIG_LIST_DATA_REQUEST =
  "GET_ADMISSION_CONFIG_LIST_DATA_REQUEST";
export const GET_ADMISSION_CONFIG_LIST_DATA_SUCCESS =
  "GET_ADMISSION_CONFIG_LIST_DATA_SUCCESS";
export const GET_ADMISSION_CONFIG_LIST_DATA_FAIL =
  "GET_ADMISSION_CONFIG_LIST_DATA_FAIL";
export const GET_ADMISSION_CONFIG_LIST_DATA_RESET =
  "GET_ADMISSION_CONFIG_LIST_DATA_RESET";

export const GET_SINGLE_ADMISSION_CONFIG_REQUEST =
  "GET_SINGLE_ADMISSION_CONFIG_REQUEST";
export const GET_SINGLE_ADMISSION_CONFIG_SUCCESS =
  "GET_SINGLE_ADMISSION_CONFIG_SUCCESS";
export const GET_SINGLE_ADMISSION_CONFIG_FAIL =
  "GET_SINGLE_ADMISSION_CONFIG_FAIL";
export const GET_SINGLE_ADMISSION_CONFIG_RESET =
  "GET_SINGLE_ADMISSION_CONFIG_RESET";

export const UPDATE_SINGLE_ADMISSION_CONFIG_REQUEST =
  "UPDATE_SINGLE_ADMISSION_CONFIG_REQUEST";
export const UPDATE_SINGLE_ADMISSION_CONFIG_SUCCESS =
  "UPDATE_SINGLE_ADMISSION_CONFIG_SUCCESS";
export const UPDATE_SINGLE_ADMISSION_CONFIG_FAIL =
  "UPDATE_SINGLE_ADMISSION_CONFIG_FAIL";
export const UPDATE_SINGLE_ADMISSION_CONFIG_RESET =
  "UPDATE_SINGLE_ADMISSION_CONFIG_RESET";

export const GET_CREATE_SINGLE_ADMISSION_CONFIG_REQUEST =
  "GET_CREATE_SINGLE_ADMISSION_CONFIG_REQUEST";
export const GET_CREATE_SINGLE_ADMISSION_CONFIG_SUCCESS =
  "GET_CREATE_SINGLE_ADMISSION_CONFIG_SUCCESS";
export const GET_CREATE_SINGLE_ADMISSION_CONFIG_FAIL =
  "GET_CREATE_SINGLE_ADMISSION_CONFIG_FAIL";
export const GET_CREATE_SINGLE_ADMISSION_CONFIG_RESET =
  "UPDATE_SINGLE_ADMISSION_CONFIG_RESET";

export const CREATE_SINGLE_ADMISSION_CONFIG_REQUEST =
  "CREATE_SINGLE_ADMISSION_CONFIG_REQUEST";
export const CREATE_SINGLE_ADMISSION_CONFIG_SUCCESS =
  "CREATE_SINGLE_ADMISSION_CONFIG_SUCCESS";
export const CREATE_SINGLE_ADMISSION_CONFIG_FAIL =
  "CREATE_SINGLE_ADMISSION_CONFIG_FAIL";
export const CREATE_SINGLE_ADMISSION_CONFIG_RESET =
  "UPDATE_SINGLE_ADMISSION_CONFIG_RESET";
