export const GET_INITIAL_ROLE_FOR_PERMISSION_REQUEST =
  "GET_INITIAL_ROLE_FOR_PERMISSION_REQUEST";
export const GET_INITIAL_ROLE_FOR_PERMISSION_SUCCESS =
  "GET_INITIAL_ROLE_FOR_PERMISSION_SUCCESS";
export const GET_INITIAL_ROLE_FOR_PERMISSION_FAIL =
  "GET_INITIAL_ROLE_FOR_PERMISSION_FAIL";
export const GET_INITIAL_ROLE_FOR_PERMISSION_RESET =
  "GET_INITIAL_ROLE_FOR_PERMISSION_FAIL";

export const GET_LIST_PERMISSION_BY_ROLE_REQUEST =
  "GET_LIST_PERMISSION_BY_ROLE_REQUEST";
export const GET_LIST_PERMISSION_BY_ROLE_SUCCESS =
  "GET_LIST_PERMISSION_BY_ROLE_SUCCESS";
export const GET_LIST_PERMISSION_BY_ROLE_FAIL =
  "GET_LIST_PERMISSION_BY_ROLE_FAIL";
export const GET_LIST_PERMISSION_BY_ROLE_RESET =
  "GET_LIST_PERMISSION_BY_ROLE_FAIL";
