export const GET_ALL_ROLE_REQUEST = "GET_ALL_ROLE_REQUEST";
export const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
export const GET_ALL_ROLE_FAIL = "GET_ALL_ROLE_FAIL";
export const GET_ALL_ROLE_RESET = "GET_ALL_ROLE_RESET";

export const ROLE_CREATE_REQUEST = "ROLE_CREATE_REQUEST";
export const ROLE_CREATE_SUCCESS = "ROLE_CREATE_SUCCESS";
export const ROLE_CREATE_FAIL = "ROLE_CREATE_FAIL";
export const ROLE_CREATE_RESET = "ROLE_CREATE_RESET";

export const GET_SINGLE_ROLE_REQUEST = "GET_SINGLE_ROLE_REQUEST";
export const GET_SINGLE_ROLE_SUCCESS = "GET_SINGLE_ROLE_SUCCESS";
export const GET_SINGLE_ROLE_FAIL = "GET_SINGLE_ROLE_FAIL";
export const GET_SINGLE_ROLE_RESET = "GET_SINGLE_ROLE_RESET";

export const UPDATE_SINGLE_ROLE_REQUEST = "UPDATE_SINGLE_ROLE_REQUEST";
export const UPDATE_SINGLE_ROLE_SUCCESS = "UPDATE_SINGLE_ROLE_SUCCESS";
export const UPDATE_SINGLE_ROLE_FAIL = "UPDATE_SINGLE_ROLE_FAIL";
export const UPDATE_SINGLE_ROLE_RESET = "UPDATE_SINGLE_ROLE_RESET";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";
export const DELETE_ROLE_RESET = "DELETE_ROLE_RESET";
