export const GET_ALL_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const GET_ALL_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const GET_ALL_ACADEMIC_YEAR_CALENDAR_FAIL =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_FAIL";
export const GET_ALL_ACADEMIC_YEAR_CALENDAR_RESET =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_RESET";

export const ACADEMIC_YEAR_CALENDAR_CREATE_REQUEST =
  "ACADEMIC_YEAR_CALENDAR_CREATE_REQUEST";
export const ACADEMIC_YEAR_CALENDAR_CREATE_SUCCESS =
  "ACADEMIC_YEAR_CALENDAR_CREATE_SUCCESS";
export const ACADEMIC_YEAR_CALENDAR_CREATE_FAIL =
  "ACADEMIC_YEAR_CALENDAR_CREATE_FAIL";
export const ACADEMIC_YEAR_CALENDAR_CREATE_RESET =
  "ACADEMIC_YEAR_CALENDAR_CREATE_RESET";

export const ACADEMIC_YEAR_CALENDAR_CREATE_POST_REQUEST =
  "ACADEMIC_YEAR_CALENDAR_CREATE_POST_REQUEST";
export const ACADEMIC_YEAR_CALENDAR_CREATE_POST_SUCCESS =
  "ACADEMIC_YEAR_CALENDAR_CREATE_POST_SUCCESS";
export const ACADEMIC_YEAR_CALENDAR_CREATE_POST_FAIL =
  "ACADEMIC_YEAR_CALENDAR_CREATE_POST_FAIL";
export const ACADEMIC_YEAR_CALENDAR_CREATE_POST_RESET =
  "ACADEMIC_YEAR_CALENDAR_CREATE_POST_RESET";

export const ACADEMIC_YEAR_CALENDAR_SEARCH_REQUEST =
  "ACADEMIC_YEAR_CALENDAR_SEARCH_REQUEST";
export const ACADEMIC_YEAR_CALENDAR_SEARCH_SUCCESS =
  "ACADEMIC_YEAR_CALENDAR_SEARCH_SUCCESS";
export const ACADEMIC_YEAR_CALENDAR_SEARCH_FAIL =
  "ACADEMIC_YEAR_CALENDAR_SEARCH_FAIL";
  export const ACADEMIC_YEAR_CALENDAR_SEARCH_RESET =
  "ACADEMIC_YEAR_CALENDAR_SEARCH_RESET";

export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET";

export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET";

export const GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_REQUEST =
  "GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_REQUEST";
export const GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_SUCCESS =
  "GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_SUCCESS";
export const GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_FAIL =
  "GET_ACADEMIC_YEAR_CALENDAR_PROGRAM_FAIL";
