export const GET_ALL_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const GET_ALL_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const GET_ALL_ACADEMIC_YEAR_CALENDAR_FAIL =
  "GET_ALL_ACADEMIC_YEAR_CALENDAR_FAIL";

export const ACADEMIC_YEAR_CALENDAR_CREATE_REQUEST =
  "ACADEMIC_YEAR_CALENDAR_CREATE_REQUEST";
export const ACADEMIC_YEAR_CALENDAR_CREATE_SUCCESS =
  "ACADEMIC_YEAR_CALENDAR_CREATE_SUCCESS";
export const ACADEMIC_YEAR_CALENDAR_CREATE_FAIL =
  "ACADEMIC_YEAR_CALENDAR_CREATE_FAIL";
export const ACADEMIC_YEAR_CALENDAR_CREATE_RESET =
  "ACADEMIC_YEAR_CALENDAR_CREATE_RESET";

export const GET_ACADEMIC_YEAR_CALENDAR_OPTION_REQUEST =
  "GET_ACADEMIC_YEAR_CALENDAR_OPTION_REQUEST";
export const GET_ACADEMIC_YEAR_CALENDAR_OPTION_SUCCESS =
  "GET_ACADEMIC_YEAR_CALENDAR_OPTION_SUCCESS";
export const GET_ACADEMIC_YEAR_CALENDAR_OPTION_FAIL =
  "GET_ACADEMIC_YEAR_CALENDAR_OPTION_FAIL";
export const GET_ACADEMIC_YEAR_CALENDAR_OPTION_RESET =
  "GET_ACADEMIC_YEAR_CALENDAR_OPTION_RESET";

export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL";
export const GET_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET =
  "GET_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET";

export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_FAIL";
export const UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET =
  "UPDATE_SINGLE_ACADEMIC_YEAR_CALENDAR_RESET";
