export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_REQUEST =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_REQUEST";
export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_SUCCESS =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_SUCCESS";
export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_FAIL =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_FAIL";
