export const GET_ALL_ACADEMIC_FACULTY_REQUEST =
  "GET_ALL_ACADEMIC_FACULTY_REQUEST";
export const GET_ALL_ACADEMIC_FACULTY_SUCCESS =
  "GET_ALL_ACADEMIC_FACULTY_SUCCESS";
export const GET_ALL_ACADEMIC_FACULTY_FAIL = "GET_ALL_ACADEMIC_FACULTY_FAIL";
export const GET_ALL_ACADEMIC_FACULTY_RESET = "GET_ALL_ACADEMIC_FACULTY_RESET";

export const ACADEMIC_FACULTY_CREATE_REQUEST =
  "ACADEMIC_FACULTY_CREATE_REQUEST";
export const ACADEMIC_FACULTY_CREATE_SUCCESS =
  "ACADEMIC_FACULTY_CREATE_SUCCESS";
export const ACADEMIC_FACULTY_CREATE_FAIL = "ACADEMIC_FACULTY_CREATE_FAIL";
export const ACADEMIC_FACULTY_CREATE_RESET = "ACADEMIC_FACULTY_CREATE_RESET";

export const GET_ACADEMIC_FACULTY_OPTION_REQUEST =
  "GET_ACADEMIC_FACULTY_OPTION_REQUEST";
export const GET_ACADEMIC_FACULTY_OPTION_SUCCESS =
  "GET_ACADEMIC_FACULTY_OPTION_SUCCESS";
export const GET_ACADEMIC_FACULTY_OPTION_FAIL =
  "GET_ACADEMIC_FACULTY_OPTION_FAIL";
export const GET_ACADEMIC_FACULTY_OPTION_RESET =
  "GET_ACADEMIC_FACULTY_OPTION_RESET";

export const GET_SINGLE_ACADEMIC_FACULTY_REQUEST =
  "GET_SINGLE_ACADEMIC_FACULTY_REQUEST";
export const GET_SINGLE_ACADEMIC_FACULTY_SUCCESS =
  "GET_SINGLE_ACADEMIC_FACULTY_SUCCESS";
export const GET_SINGLE_ACADEMIC_FACULTY_FAIL =
  "GET_SINGLE_ACADEMIC_FACULTY_FAIL";
export const GET_SINGLE_ACADEMIC_FACULTY_RESET =
  "GET_SINGLE_ACADEMIC_FACULTY_RESET";

export const UPDATE_SINGLE_ACADEMIC_FACULTY_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_FACULTY_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_FACULTY_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_FACULTY_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_FACULTY_FAIL =
  "UPDATE_SINGLE_ACADEMIC_FACULTY_FAIL";
export const UPDATE_SINGLE_ACADEMIC_FACULTY_RESET =
  "UPDATE_SINGLE_ACADEMIC_FACULTY_RESET";
