export const GET_ALL_EDUCATION_REQUEST = 'GET_ALL_EDUCATION_REQUEST';
export const GET_ALL_EDUCATION_SUCCESS = 'GET_ALL_EDUCATION_SUCCESS';
export const GET_ALL_EDUCATION_FAIL = 'GET_ALL_EDUCATION_FAIL';
export const GET_ALL_EDUCATION_RESET = 'GET_ALL_EDUCATION_RESET';