export const GET_INITIAL_STUDENT_REGISTRATION_DATA_REQUEST =
  "GET_INITIAL_STUDENT_REGISTRATION_DATA_REQUEST";
export const GET_INITIAL_STUDENT_REGISTRATION_DATA_SUCCESS =
  "GET_INITIAL_STUDENT_REGISTRATION_DATA_SUCCESS";
export const GET_INITIAL_STUDENT_REGISTRATION_DATA_FAIL =
  "GET_INITIAL_STUDENT_REGISTRATION_DATA_FAIL";

export const GET_STUDENT_REGISTRATION_DATA_REQUEST =
  "GET_STUDENT_REGISTRATION_DATA_REQUEST";
export const GET_STUDENT_REGISTRATION_DATA_SUCCESS =
  "GET_STUDENT_REGISTRATION_DATA_SUCCESS";
export const GET_STUDENT_REGISTRATION_DATA_FAIL =
  "GET_STUDENT_REGISTRATION_DATA_FAIL";
  export const GET_STUDENT_REGISTRATION_DATA_RESET =
  "GET_STUDENT_REGISTRATION_DATA_RESET";
  

export const GET_SINGLE_STUDENT_REGISTRATION_DATA_REQUEST =
  "GET_SINGLE_STUDENT_REGISTRATION_DATA_REQUEST";
export const GET_SINGLE_STUDENT_REGISTRATION_DATA_SUCCESS =
  "GET_SINGLE_STUDENT_REGISTRATION_DATA_SUCCESS";
export const GET_SINGLE_STUDENT_REGISTRATION_DATA_FAIL =
  "GET_SINGLE_STUDENT_REGISTRATION_DATA_FAIL";
export const GET_SINGLE_STUDENT_REGISTRATION_DATA_RESET =
  "GET_SINGLE_STUDENT_REGISTRATION_DATA_RESET";

export const SINGLE_STUDENT_REGISTRATION_CREATE_REQUEST =
  "SINGLE_STUDENT_REGISTRATION_CREATE_REQUEST";
export const SINGLE_STUDENT_REGISTRATION_CREATE_SUCCESS =
  "SINGLE_STUDENT_REGISTRATION_CREATE_SUCCESS";
export const SINGLE_STUDENT_REGISTRATION_CREATE_FAIL =
  "SINGLE_STUDENT_REGISTRATION_CREATE_FAIL";

export const SINGLE_STUDENT_REGISTRATION_EDIT_REQUEST =
  "SINGLE_STUDENT_REGISTRATION_EDIT_REQUEST";
export const SINGLE_STUDENT_REGISTRATION_EDIT_SUCCESS =
  "SINGLE_STUDENT_REGISTRATION_EDIT_SUCCESS";
export const SINGLE_STUDENT_REGISTRATION_EDIT_FAIL =
  "SINGLE_STUDENT_REGISTRATION_EDIT_FAIL";
export const SINGLE_STUDENT_REGISTRATION_EDIT_RESET =
  "SINGLE_STUDENT_REGISTRATION_EDIT_RESET";

export const GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_REQUEST =
  "GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_REQUEST";
export const GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_SUCCESS =
  "GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_SUCCESS";
export const GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_FAIL =
  "GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_FAIL";
export const GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_RESET =
  "GET_CREATE_SINGLE_STUDENT_REGISTRATION_DATA_RESET";

export const CREATE_SINGLE_STUDENT_REGISTRATION_REQUEST =
  "CREATE_SINGLE_STUDENT_REGISTRATION_REQUEST";
export const CREATE_SINGLE_STUDENT_REGISTRATION_SUCCESS =
  "CREATE_SINGLE_STUDENT_REGISTRATION_SUCCESS";
export const CREATE_SINGLE_STUDENT_REGISTRATION_FAIL =
  "CREATE_SINGLE_STUDENT_REGISTRATION_FAIL";
export const CREATE_SINGLE_STUDENT_REGISTRATION_RESET =
  "CREATE_SINGLE_STUDENT_REGISTRATION_RESET";

export const CHECK_REGISTRATION_FOR_STUDENT_REQUEST =
  "CHECK_REGISTRATION_FOR_STUDENT_REQUEST";
export const CHECK_REGISTRATION_FOR_STUDENT_SUCCESS =
  "CHECK_REGISTRATION_FOR_STUDENT_SUCCESS";
export const CHECK_REGISTRATION_FOR_STUDENT_FAIL =
  "CHECK_REGISTRATION_FOR_STUDENT_FAIL";
export const CHECK_REGISTRATION_FOR_STUDENT_RESET =
  "CHECK_REGISTRATION_FOR_STUDENT_RESET";

export const CHECK_ROLLNO_FOR_STUDENT_REQUEST =
  "CHECK_ROLLNO_FOR_STUDENT_REQUEST";
export const CHECK_ROLLNO_FOR_STUDENT_SUCCESS =
  "CHECK_ROLLNO_FOR_STUDENT_SUCCESS";
export const CHECK_ROLLNO_FOR_STUDENT_FAIL = "CHECK_ROLLNO_FOR_STUDENT_FAIL";
export const CHECK_ROLLNO_FOR_STUDENT_RESET = "CHECK_ROLLNO_FOR_STUDENT_RESET";

export const CHECK_ACADEMIC_YEAR_FOR_STUDENT_REQUEST =
  "CHECK_ACADEMIC_YEAR_FOR_STUDENT_REQUEST";
export const CHECK_ACADEMIC_YEAR_FOR_STUDENT_SUCCESS =
  "CHECK_ACADEMIC_YEAR_FOR_STUDENT_SUCCESS";
export const CHECK_ACADEMIC_YEAR_FOR_STUDENT_FAIL = "CHECK_ACADEMIC_YEAR_FOR_STUDENT_FAIL";
export const CHECK_ACADEMIC_YEAR_FOR_STUDENT_RESET = "CHECK_ACADEMIC_YEAR_FOR_STUDENT_RESET";
