export const GET_INITIAL_LEVEL_TEST_DATA_REQUEST =
  "GET_INITIAL_LEVEL_TEST_DATA_REQUEST";
export const GET_INITIAL_LEVEL_TEST_DATA_SUCCESS =
  "GET_INITIAL_LEVEL_TEST_DATA_SUCCESS";
export const GET_INITIAL_LEVEL_TEST_DATA_FAIL =
  "GET_INITIAL_LEVEL_TEST_DATA_FAIL";

export const GET_BULK_LEVEL_TEST_DATA_REQUEST =
  "GET_BULK_LEVEL_TEST_DATA_REQUEST";
export const GET_BULK_LEVEL_TEST_DATA_SUCCESS =
  "GET_BULK_LEVEL_TEST_DATA_SUCCESS";
export const GET_BULK_LEVEL_TEST_DATA_FAIL = "GET_BULK_LEVEL_TEST_DATA_FAIL";
export const GET_BULK_LEVEL_TEST_DATA_RESET = "GET_BULK_LEVEL_TEST_DATA_RESET";

export const POST_BULK_LEVEL_TEST_DATA_REQUEST =
  "POST_BULK_LEVEL_TEST_DATA_REQUEST";
export const POST_BULK_LEVEL_TEST_DATA_SUCCESS =
  "POST_BULK_LEVEL_TEST_DATA_SUCCESS";
export const POST_BULK_LEVEL_TEST_DATA_FAIL = "POST_BULK_LEVEL_TEST_DATA_FAIL";
export const POST_BULK_LEVEL_TEST_DATA_RESET =
  "POST_BULK_LEVEL_TEST_DATA_RESET";
