export const GET_INITIAL_LEVEL_TEST_DATA_REQUEST =
  "GET_INITIAL_LEVEL_TEST_DATA_REQUEST";
export const GET_INITIAL_LEVEL_TEST_DATA_SUCCESS =
  "GET_INITIAL_LEVEL_TEST_DATA_SUCCESS";
export const GET_INITIAL_LEVEL_TEST_DATA_FAIL =
  "GET_INITIAL_LEVEL_TEST_DATA_FAIL";
