export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_REQUEST =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_REQUEST";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_SUCCESS =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_SUCCESS";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_FAIL =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_FAIL";
export const GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_RESET =
  "GET_ALL_STUDEN_MONTHLY_PRESENT_SHEET_RESET";

export const GET_SUBJECT_OPTIONS_FOR_SELECT_REQUEST =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_REQUEST";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_SUCCESS =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_SUCCESS";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_FAIL =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_FAIL";
export const GET_SUBJECT_OPTIONS_FOR_SELECT_RESET =
  "GET_SUBJECT_OPTIONS_FOR_SELECT_RESET";
