export const GET_ALL_POSITION_REQUEST = "GET_ALL_POSITION_REQUEST";
export const GET_ALL_POSITION_SUCCESS = "GET_ALL_POSITION_SUCCESS";
export const GET_ALL_POSITION_FAIL = "GET_ALL_POSITION_FAIL";

export const POSITION_CREATE_REQUEST = "POSITION_CREATE_REQUEST";
export const POSITION_CREATE_SUCCESS = "POSITION_CREATE_SUCCESS";
export const POSITION_CREATE_FAIL = "POSITION_CREATE_FAIL";
export const POSITION_CREATE_RESET = "POSITION_CREATE_RESET";
