export const GET_ALL_POSITION_REQUEST = "GET_ALL_POSITION_REQUEST";
export const GET_ALL_POSITION_SUCCESS = "GET_ALL_POSITION_SUCCESS";
export const GET_ALL_POSITION_FAIL = "GET_ALL_POSITION_FAIL";
export const GET_ALL_POSITION_RESET = "GET_ALL_POSITION_RESET";

export const POSITION_CREATE_REQUEST = "POSITION_CREATE_REQUEST";
export const POSITION_CREATE_SUCCESS = "POSITION_CREATE_SUCCESS";
export const POSITION_CREATE_FAIL = "POSITION_CREATE_FAIL";
export const POSITION_CREATE_RESET = "POSITION_CREATE_RESET";

export const GET_SINGLE_POSITION_REQUEST = "GET_SINGLE_POSITION_REQUEST";
export const GET_SINGLE_POSITION_SUCCESS = "GET_SINGLE_POSITION_SUCCESS";
export const GET_SINGLE_POSITION_FAIL = "GET_SINGLE_POSITION_FAIL";
export const GET_SINGLE_POSITION_RESET = "GET_SINGLE_POSITION_RESET";

export const UPDATE_SINGLE_POSITION_REQUEST = "UPDATE_SINGLE_POSITION_REQUEST";
export const UPDATE_SINGLE_POSITION_SUCCESS = "UPDATE_SINGLE_POSITION_SUCCESS";
export const UPDATE_SINGLE_POSITION_FAIL = "UPDATE_SINGLE_POSITION_FAIL";
export const UPDATE_SINGLE_POSITION_RESET = "UPDATE_SINGLE_POSITION_RESET";
