export const GET_INITIAL_EXAM_APPORVAL_DATA_REQUEST =
  "GET_INITIAL_EXAM_APPORVAL_DATA_REQUEST";
export const GET_INITIAL_EXAM_APPORVAL_DATA_SUCCESS =
  "GET_INITIAL_EXAM_APPORVAL_DATA_SUCCESS";
export const GET_INITIAL_EXAM_APPORVAL_DATA_FAIL =
  "GET_INITIAL_EXAM_APPORVAL_DATA_FAIL";

export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_REQUEST =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_REQUEST";
export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_SUCCESS =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_SUCCESS";
export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_FAIL =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_FAIL";
