export const GET_INITIAL_EXAM_APPORVAL_DATA_REQUEST =
  "GET_INITIAL_EXAM_APPORVAL_DATA_REQUEST";
export const GET_INITIAL_EXAM_APPORVAL_DATA_SUCCESS =
  "GET_INITIAL_EXAM_APPORVAL_DATA_SUCCESS";
export const GET_INITIAL_EXAM_APPORVAL_DATA_FAIL =
  "GET_INITIAL_EXAM_APPORVAL_DATA_FAIL";

export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_REQUEST =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_REQUEST";
export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_SUCCESS =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_SUCCESS";
export const GET_ALL_EXAM_APPROVAL_SEARCHDATA_FAIL =
  "GET_ALL_EXAM_APPROVAL_SEARCHDATA_FAIL";

export const GET_BULK_EXAM_APPROVAL_REQUEST = "GET_BULK_EXAM_APPROVAL_REQUEST";
export const GET_BULK_EXAM_APPROVAL_SUCCESS = "GET_BULK_EXAM_APPROVAL_SUCCESS";
export const GET_BULK_EXAM_APPROVAL_FAIL = "GET_BULK_EXAM_APPROVAL_FAIL";
export const GET_BULK_EXAM_APPROVAL_RESET = "GET_BULK_EXAM_APPROVAL_RESET";

export const POST_BULK_EXAM_APPROVAL_REQUEST =
  "POST_BULK_EXAM_APPROVAL_REQUEST";
export const POST_BULK_EXAM_APPROVAL_SUCCESS =
  "POST_BULK_EXAM_APPROVAL_SUCCESS";
export const POST_BULK_EXAM_APPROVAL_FAIL = "POST_BULK_EXAM_APPROVAL_FAIL";
export const POST_BULK_EXAM_APPROVAL_RESET = "POST_BULK_EXAM_APPROVAL_RESET";
