export const GET_ALL_EMAIL_REQUEST = 'GET_ALL_EMAIL_REQUEST';
export const GET_ALL_EMAIL_SUCCESS = 'GET_ALL_EMAIL_SUCCESS';
export const GET_ALL_EMAIL_FAIL = 'GET_ALL_EMAIL_FAIL';
export const GET_ALL_EMAIL_RESET = 'GET_ALL_EMAIL_RESET';

export const GET_SINGLE_EMAIL_REQUEST = 'GET_SINGLE_EMAIL_REQUEST';
export const GET_SINGLE_EMAIL_SUCCESS = 'GET_SINGLE_EMAIL_SUCCESS';
export const GET_SINGLE_EMAIL_FAIL = 'GET_SINGLE_EMAIL_FAIL';
export const GET_SINGLE_EMAIL_RESET = 'GET_SINGLE_EMAIL_RESET';