export const GET_ALL_ASSIGN_STUDENT_SUBJECT_REQUEST =
  "GET_ALL_ASSIGN_STUDENT_SUBJECT_REQUEST";
export const GET_ALL_ASSIGN_STUDENT_SUBJECT_SUCCESS =
  "GET_ALL_ASSIGN_STUDENT_SUBJECT_SUCCESS";
export const GET_ALL_ASSIGN_STUDENT_SUBJECT_FAIL =
  "GET_ALL_ASSIGN_STUDENT_SUBJECT_FAIL";
export const GET_ALL_ASSIGN_STUDENT_SUBJECT_RESET =
  "GET_ALL_ASSIGN_STUDENT_SUBJECT_RESET";