export const GET_ALL_MOBILE_USER_REQUEST = "GET_ALL_MOBILE_USER_REQUEST";
export const GET_ALL_MOBILE_USER_SUCCESS = "GET_ALL_MOBILE_USER_SUCCESS";
export const GET_ALL_MOBILE_USER_FAIL = "GET_ALL_MOBILE_USER_FAIL";
export const GET_ALL_MOBILE_USER_RESET = "GET_ALL_MOBILE_USER_RESET";

export const GET_LIST_MOBILE_USER_REQUEST = "GET_LIST_MOBILE_USER_REQUEST";
export const GET_LIST_MOBILE_USER_SUCCESS = "GET_LIST_MOBILE_USER_SUCCESS";
export const GET_LIST_MOBILE_USER_FAIL = "GET_LIST_MOBILE_USER_FAIL";
export const GET_LIST_MOBILE_USER_RESET = "GET_LIST_MOBILE_USER_RESET";

export const GET_SINGLE_EDIT_MOBILE_USER_REQUEST = "GET_SINGLE_EDIT_MOBILE_USER_REQUEST";
export const GET_SINGLE_EDIT_MOBILE_USER_SUCCESS = "GET_SINGLE_EDIT_MOBILE_USER_SUCCESS";
export const GET_SINGLE_EDIT_MOBILE_USER_FAIL = "GET_SINGLE_EDIT_MOBILE_USER_FAIL";
export const GET_SINGLE_EDIT_MOBILE_USER_RESET = "GET_SINGLE_EDIT_MOBILE_USER_RESET";

export const PUT_MOBILE_USER_REQUEST = "PUT_MOBILE_USER_REQUEST";
export const PUT_MOBILE_USER_SUCCESS = "PUT_MOBILE_USER_SUCCESS";
export const PUT_MOBILE_USER_FAIL = "PUT_MOBILE_USER_FAIL";
export const PUT_MOBILE_USER_RESET = "PUT_MOBILE_USER_RESET";