export const GET_ALL_REASSOCIATE_STUDENTS_REQUEST =
  "GET_ALL_REASSOCIATE_STUDENTS_REQUEST";
export const GET_ALL_REASSOCIATE_STUDENTS_SUCCESS =
  "GET_ALL_REASSOCIATE_STUDENTS_SUCCESS";
export const GET_ALL_REASSOCIATE_STUDENTS_FAIL =
  "GET_ALL_REASSOCIATE_STUDENTS_FAIL";

export const GET_REASSOCIATE_STUDENTS_LISTS_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LISTS_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LISTS_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LISTS_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LISTS_FAIL =
  "GET_REASSOCIATE_STUDENTS_LISTS_FAIL";

export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_FAIL =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_FAIL";

export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_FAIL =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_FAIL";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_RESET =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_RESET";
