export const GET_ALL_REASSOCIATE_STUDENTS_REQUEST =
  "GET_ALL_REASSOCIATE_STUDENTS_REQUEST";
export const GET_ALL_REASSOCIATE_STUDENTS_SUCCESS =
  "GET_ALL_REASSOCIATE_STUDENTS_SUCCESS";
export const GET_ALL_REASSOCIATE_STUDENTS_FAIL =
  "GET_ALL_REASSOCIATE_STUDENTS_FAIL";

export const GET_REASSOCIATE_STUDENTS_LISTS_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LISTS_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LISTS_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LISTS_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LISTS_FAIL =
  "GET_REASSOCIATE_STUDENTS_LISTS_FAIL";
  export const GET_REASSOCIATE_STUDENTS_LISTS_RESET =
  "GET_REASSOCIATE_STUDENTS_LISTS_RESET";

export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_FAIL =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_FAIL";
  export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_RESET =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_RESET";

export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_REQUEST =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_REQUEST";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_SUCCESS =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_SUCCESS";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_FAIL =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_FAIL";
export const GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_RESET =
  "GET_REASSOCIATE_STUDENTS_LEVEL_UP_POST_RESET";

export const GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_REQUEST =
  "GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_REQUEST";
export const GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_SUCCESS =
  "GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_SUCCESS";
export const GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_FAIL =
  "GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_FAIL";
export const GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_RESET =
  "GET_SINGLE_TO_EDIT_REASSOCIATE_STUDENTS_RESET";

  export const PUT_REASSOCIATE_STUDENTS_REQUEST =
  "PUT_REASSOCIATE_STUDENTS_REQUEST";
export const PUT_REASSOCIATE_STUDENTS_SUCCESS =
  "PUT_REASSOCIATE_STUDENTS_SUCCESS";
export const PUT_REASSOCIATE_STUDENTS_FAIL =
  "PUT_REASSOCIATE_STUDENTS_FAIL";
export const PUT_REASSOCIATE_STUDENTS_RESET =
  "PUT_REASSOCIATE_STUDENTS_RESET";