export const GET_ALL_SMS_ANNOUNCEMENT_REQUEST =
  "GET_ALL_SMS_ANNOUNCEMENT_REQUEST";
export const GET_ALL_SMS_ANNOUNCEMENT_SUCCESS =
  "GET_ALL_SMS_ANNOUNCEMENT_SUCCESS";
export const GET_ALL_SMS_ANNOUNCEMENT_FAIL = "GET_ALL_SMS_ANNOUNCEMENT_FAIL";
export const GET_ALL_SMS_ANNOUNCEMENT_RESET = "GET_ALL_SMS_ANNOUNCEMENT_RESET";

export const GET_LIST_SMS_ANNOUNCEMENT_REQUEST =
  "GET_LIST_SMS_ANNOUNCEMENT_REQUEST";
export const GET_LIST_SMS_ANNOUNCEMENT_SUCCESS =
  "GET_LIST_SMS_ANNOUNCEMENT_SUCCESS";
export const GET_LIST_SMS_ANNOUNCEMENT_FAIL = "GET_LIST_SMS_ANNOUNCEMENT_FAIL";
export const GET_LIST_SMS_ANNOUNCEMENT_RESET =
  "GET_LIST_SMS_ANNOUNCEMENT_RESET";

export const SMS_ANNOUNCEMENT_FCM_REQUEST = "SMS_ANNOUNCEMENT_FCM_REQUEST";
export const SMS_ANNOUNCEMENT_FCM_SUCCESS = "SMS_ANNOUNCEMENT_FCM_SUCCESS";
export const SMS_ANNOUNCEMENT_FCM_FAIL = "SMS_ANNOUNCEMENT_FCM_FAIL";
export const SMS_ANNOUNCEMENT_FCM_RESET = "SMS_ANNOUNCEMENT_FCM_RESET";

export const SMS_ANNOUNCEMENT_CREATE_REQUEST =
  "SMS_ANNOUNCEMENT_CREATE_REQUEST";
export const SMS_ANNOUNCEMENT_CREATE_SUCCESS =
  "SMS_ANNOUNCEMENT_CREATE_SUCCESS";
export const SMS_ANNOUNCEMENT_CREATE_FAIL = "SMS_ANNOUNCEMENT_CREATE_FAIL";
export const SMS_ANNOUNCEMENT_CREATE_RESET = "SMS_ANNOUNCEMENT_CREATE_RESET";

export const GET_SINGLE_SMS_ANNOUNCEMENT_REQUEST =
  "GET_SINGLE_SMS_ANNOUNCEMENT_REQUEST";
export const GET_SINGLE_SMS_ANNOUNCEMENT_SUCCESS =
  "GET_SINGLE_SMS_ANNOUNCEMENT_SUCCESS";
export const GET_SINGLE_SMS_ANNOUNCEMENT_FAIL =
  "GET_SINGLE_SMS_ANNOUNCEMENT_FAIL";
export const GET_SINGLE_SMS_ANNOUNCEMENT_RESET =
  "GET_SINGLE_SMS_ANNOUNCEMENT_RESET";

export const UPDATE_SINGLE_SMS_ANNOUNCEMENT_REQUEST =
  "UPDATE_SINGLE_SMS_ANNOUNCEMENT_REQUEST";
export const UPDATE_SINGLE_SMS_ANNOUNCEMENT_SUCCESS =
  "UPDATE_SINGLE_SMS_ANNOUNCEMENT_SUCCESS";
export const UPDATE_SINGLE_SMS_ANNOUNCEMENT_FAIL =
  "UPDATE_SINGLE_SMS_ANNOUNCEMENT_FAIL";
export const UPDATE_SINGLE_SMS_ANNOUNCEMENT_RESET =
  "UPDATE_SINGLE_SMS_ANNOUNCEMENT_RESET";
