export const GET_ALL_EMPLOYEE_TYPE_REQUEST = "GET_ALL_EMPLOYEE_TYPE_REQUEST";
export const GET_ALL_EMPLOYEE_TYPE_SUCCESS = "GET_ALL_EMPLOYEE_TYPE_SUCCESS";
export const GET_ALL_EMPLOYEE_TYPE_FAIL = "GET_ALL_EMPLOYEE_TYPE_FAIL";
