export const GET_ALL_EMPLOYEE_TYPE_REQUEST = "GET_ALL_EMPLOYEE_TYPE_REQUEST";
export const GET_ALL_EMPLOYEE_TYPE_SUCCESS = "GET_ALL_EMPLOYEE_TYPE_SUCCESS";
export const GET_ALL_EMPLOYEE_TYPE_FAIL = "GET_ALL_EMPLOYEE_TYPE_FAIL";
export const GET_ALL_EMPLOYEE_TYPE_RESET = "GET_ALL_EMPLOYEE_TYPE_RESET";

export const EMPLOYEE_TYPE_CREATE_REQUEST = "EMPLOYEE_TYPE_CREATE_REQUEST";
export const EMPLOYEE_TYPE_CREATE_SUCCESS = "EMPLOYEE_TYPE_CREATE_SUCCESS";
export const EMPLOYEE_TYPE_CREATE_FAIL = "EMPLOYEE_TYPE_CREATE_FAIL";
export const EMPLOYEE_TYPE_CREATE_RESET = "EMPLOYEE_TYPE_CREATE_RESET";

export const GET_SINGLE_EMPLOYEE_TYPE_REQUEST =
  "GET_SINGLE_EMPLOYEE_TYPE_REQUEST";
export const GET_SINGLE_EMPLOYEE_TYPE_SUCCESS =
  "GET_SINGLE_EMPLOYEE_TYPE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_TYPE_FAIL = "GET_SINGLE_EMPLOYEE_TYPE_FAIL";
export const GET_SINGLE_EMPLOYEE_TYPE_RESET = "GET_SINGLE_EMPLOYEE_TYPE_RESET";

export const UPDATE_SINGLE_EMPLOYEE_TYPE_REQUEST =
  "UPDATE_SINGLE_EMPLOYEE_TYPE_REQUEST";
export const UPDATE_SINGLE_EMPLOYEE_TYPE_SUCCESS =
  "UPDATE_SINGLE_EMPLOYEE_TYPE_SUCCESS";
export const UPDATE_SINGLE_EMPLOYEE_TYPE_FAIL =
  "UPDATE_SINGLE_EMPLOYEE_TYPE_FAIL";
export const UPDATE_SINGLE_EMPLOYEE_TYPE_RESET =
  "UPDATE_SINGLE_EMPLOYEE_TYPE_RESET";

export const DELETE_EMPLOYEE_TYPE_REQUEST =
  "DELETE_EMPLOYEE_TYPE_REQUEST";
export const DELETE_EMPLOYEE_TYPE_SUCCESS =
  "DELETE_EMPLOYEE_TYPE_SUCCESS";
export const DELETE_EMPLOYEE_TYPE_FAIL =
  "DELETE_EMPLOYEE_TYPE_FAIL";
export const DELETE_EMPLOYEE_TYPE_RESET =
  "DELETE_EMPLOYEE_TYPE_RESET";
