export const GET_ALL_ACADEMIC_SECTION_REQUEST =
  "GET_ALL_ACADEMIC_SECTION_REQUEST";
export const GET_ALL_ACADEMIC_SECTION_SUCCESS =
  "GET_ALL_ACADEMIC_SECTION_SUCCESS";
export const GET_ALL_ACADEMIC_SECTION_FAIL = "GET_ALL_ACADEMIC_SECTION_FAIL";
