export const GET_ALL_ACADEMIC_SECTION_REQUEST =
  "GET_ALL_ACADEMIC_SECTION_REQUEST";
export const GET_ALL_ACADEMIC_SECTION_SUCCESS =
  "GET_ALL_ACADEMIC_SECTION_SUCCESS";
export const GET_ALL_ACADEMIC_SECTION_FAIL = "GET_ALL_ACADEMIC_SECTION_FAIL";
export const GET_ALL_ACADEMIC_SECTION_RESET = "GET_ALL_ACADEMIC_SECTION_RESET";

export const ACADEMIC_SECTION_CREATE_REQUEST =
  "ACADEMIC_SECTION_CREATE_REQUEST";
export const ACADEMIC_SECTION_CREATE_SUCCESS =
  "ACADEMIC_SECTION_CREATE_SUCCESS";
export const ACADEMIC_SECTION_CREATE_FAIL = "ACADEMIC_SECTION_CREATE_FAIL";
export const ACADEMIC_SECTION_CREATE_RESET = "ACADEMIC_SECTION_CREATE_RESET";

export const GET_SINGLE_ACADEMIC_SECTION_REQUEST =
  "GET_SINGLE_ACADEMIC_SECTION_REQUEST";
export const GET_SINGLE_ACADEMIC_SECTION_SUCCESS =
  "GET_SINGLE_ACADEMIC_SECTION_SUCCESS";
export const GET_SINGLE_ACADEMIC_SECTION_FAIL =
  "GET_SINGLE_ACADEMIC_SECTION_FAIL";
export const GET_SINGLE_ACADEMIC_SECTION_RESET =
  "GET_SINGLE_ACADEMIC_SECTION_RESET";

export const UPDATE_SINGLE_ACADEMIC_SECTION_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_SECTION_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_SECTION_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_SECTION_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_SECTION_FAIL =
  "UPDATE_SINGLE_ACADEMIC_SECTION_FAIL";
export const UPDATE_SINGLE_ACADEMIC_SECTION_RESET =
  "UPDATE_SINGLE_ACADEMIC_SECTION_RESET";
