export const GET_ALL_CONTACTADDRESS_REQUEST = 'GET_ALL_CONTACTADDRESS_REQUEST';
export const GET_ALL_CONTACTADDRESS_SUCCESS = 'GET_ALL_CONTACTADDRESS_SUCCESS';
export const GET_ALL_CONTACTADDRESS_FAIL = 'GET_ALL_CONTACTADDRESS_FAIL';
export const GET_ALL_CONTACTADDRESS_RESET = 'GET_ALL_CONTACTADDRESS_RESET';