export const GET_All_ACADEMIC_SUBJECT_REQUEST =
  "GET_All_ACADEMIC_SUBJECT_REQUEST";
export const GET_ALL_ACADEMIC_SUBJECT_SUCCES =
  "GET_ALL_ACADEMIC_SUBJECT_SUCCES";
export const GET_ALL_ACADEMIC_SUBJECT_FAIL = "GET_ALL_ACADEMIC_SUBJECT_FAIL";
export const GET_ALL_ACADEMIC_SUBJECT_RESET = "GET_ALL_ACADEMIC_SUBJECT_RESET";

export const GET_SINGLE_ACADEMIC_SUBJECT_REQUEST =
  "GET_SINGLE_ACADEMIC_SUBJECT_REQUEST";
export const GET_SINGLE_ACADEMIC_SUBJECT_SUCCESS =
  "GET_SINGLE_ACADEMIC_SUBJECT_SUCCESS";
export const GET_SINGLE_ACADEMIC_SUBJECT_FAIL =
  "GET_SINGLE_ACADEMIC_SUBJECT_FAIL";
export const GET_SINGLE_ACADEMIC_SUBJECT_RESET =
  "GET_SINGLE_ACADEMIC_SUBJECT_RESET";

export const ACADEMIC_SUBJECT_CREATE_REQUEST =
  "ACADEMIC_SUBJECT_CREATE_REQUEST";
export const ACADEMIC_SUBJECT_CREATE_SUCCESS =
  "ACADEMIC_SUBJECT_CREATE_SUCCESS";
export const ACADEMIC_SUBJECT_CREATE_FAIL = "ACADEMIC_SUBJECT_CREATE_FAIL";
export const ACADEMIC_SUBJECT_CREATE_RESET = "ACADEMIC_SUBJECT_CREATE_RESET";

export const UPDATE_SINGLE_ACADEMIC_SUBJECT_REQUEST =
  "UPDATE_SINGLE_ACADEMIC_SUBJECT_REQUEST";
export const UPDATE_SINGLE_ACADEMIC_SUBJECT_SUCCESS =
  "UPDATE_SINGLE_ACADEMIC_SUBJECT_SUCCESS";
export const UPDATE_SINGLE_ACADEMIC_SUBJECT_FAIL =
  "UPDATE_SINGLE_ACADEMIC_SUBJECT_FAIL";
export const UPDATE_SINGLE_ACADEMIC_SUBJECT_RESET =
  "UPDATE_SINGLE_ACADEMIC_SUBJECT_RESET";
