export const GET_INITIAL_EXAM_RESULT_DATA_REQUEST =
  "GET_INITIAL_EXAM_RESULT_DATA_REQUEST";
export const GET_INITIAL_EXAM_RESULT_DATA_SUCCESS =
  "GET_INITIAL_EXAM_RESULT_DATA_SUCCESS";
export const GET_INITIAL_EXAM_RESULT_DATA_FAIL =
  "GET_INITIAL_EXAM_RESULT_DATA_FAIL";

export const GET_EVENT_FOR_EXAM_MARK_REQUEST =
  "GET_EVENT_FOR_EXAM_MARK_REQUEST";
export const GET_EVENT_FOR_EXAM_MARK_SUCCESS =
  "GET_EVENT_FOR_EXAM_MARK_SUCCESS";
export const GET_EVENT_FOR_EXAM_MARK_FAIL = "GET_EVENT_FOR_EXAM_MARK_FAIL";
export const GET_EVENT_FOR_EXAM_MARK_RESET = "GET_EVENT_FOR_EXAM_MARK_RESET";

export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_REQUEST =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_REQUEST";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_SUCCESS =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_SUCCESS";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_FAIL =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_FAIL";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_RESET =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_RESET";

export const GET_EXAM_RESULT_LIST_REQUEST = "GET_EXAM_RESULT_LIST_REQUEST";
export const GET_EXAM_RESULT_LIST_SUCCESS = "GET_EXAM_RESULT_LIST_SUCCESS";
export const GET_EXAM_RESULT_LIST_FAIL = "GET_EXAM_RESULT_LIST_FAIL";
