export const GET_INITIAL_EXAM_RESULT_DATA_REQUEST =
  "GET_INITIAL_EXAM_RESULT_DATA_REQUEST";
export const GET_INITIAL_EXAM_RESULT_DATA_SUCCESS =
  "GET_INITIAL_EXAM_RESULT_DATA_SUCCESS";
export const GET_INITIAL_EXAM_RESULT_DATA_FAIL =
  "GET_INITIAL_EXAM_RESULT_DATA_FAIL";

export const GET_EVENT_FOR_EXAM_MARK_REQUEST =
  "GET_EVENT_FOR_EXAM_MARK_REQUEST";
export const GET_EVENT_FOR_EXAM_MARK_SUCCESS =
  "GET_EVENT_FOR_EXAM_MARK_SUCCESS";
export const GET_EVENT_FOR_EXAM_MARK_FAIL = "GET_EVENT_FOR_EXAM_MARK_FAIL";
export const GET_EVENT_FOR_EXAM_MARK_RESET = "GET_EVENT_FOR_EXAM_MARK_RESET";

export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_REQUEST =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_REQUEST";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_SUCCESS =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_SUCCESS";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_FAIL =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_FAIL";
export const GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_RESET =
  "GET_INITIAL_EXAM_RESULT_STUDENT_OPTIONS_RESET";

export const GET_EXAM_RESULT_LIST_REQUEST = "GET_EXAM_RESULT_LIST_REQUEST";
export const GET_EXAM_RESULT_LIST_SUCCESS = "GET_EXAM_RESULT_LIST_SUCCESS";
export const GET_EXAM_RESULT_LIST_FAIL = "GET_EXAM_RESULT_LIST_FAIL";
export const GET_EXAM_RESULT_LIST_RESET = "GET_EXAM_RESULT_LIST_RESET";

export const GET_EXAM_LEDGER_HEADER_REQUEST = "GET_EXAM_LEDGER_HEADER_REQUEST";
export const GET_EXAM_LEDGER_HEADER_SUCCESS = "GET_EXAM_LEDGER_HEADER_SUCCESS";
export const GET_EXAM_LEDGER_HEADER_FAIL = "GET_EXAM_LEDGER_HEADER_FAIL";
export const GET_EXAM_LEDGER_HEADER_RESET = "GET_EXAM_LEDGER_HEADER_RESET";

export const PRINT_EXAM_RESULT_REQUEST = "PRINT_EXAM_RESULT_REQUEST";
export const PRINT_EXAM_RESULT_SUCCESS = "PRINT_EXAM_RESULT_SUCCESS";
export const PRINT_EXAM_RESULT_FAIL = "PRINT_EXAM_RESULT_FAIL";
export const PRINT_EXAM_RESULT_RESET = "PRINT_EXAM_RESULT_RESET";

export const PRINT_EXAM_RESULT_COUNT_REQUEST =
  "PRINT_EXAM_RESULT_COUNT_REQUEST";
export const PRINT_EXAM_RESULT_COUNT_SUCCESS =
  "PRINT_EXAM_RESULT_COUNT_SUCCESS";
export const PRINT_EXAM_RESULT_COUNT_FAIL = "PRINT_EXAM_RESULT_COUNT_FAIL";
export const PRINT_EXAM_RESULT_COUNT_RESET = "PRINT_EXAM_RESULT_COUNT_RESET";

export const PRINT_FINAL_RESULT_REQUEST = "PRINT_FINAL_RESULT_REQUEST";
export const PRINT_FINAL_RESULT_SUCCESS = "PRINT_FINAL_RESULT_SUCCESS";
export const PRINT_FINAL_RESULT_FAIL = "PRINT_FINAL_RESULT_FAIL";
export const PRINT_FINAL_RESULT_RESET = "PRINT_FINAL_RESULT_RESET";
