export const testExamJson = {
  $id: "1",
  dbModelLst: [
    {
      $id: "2",
      RollNo: "1",
      idShift: 2,
      StudentName: "Pratyush Ale Magar",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 41234,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10838,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 161,
      TotalAvgObtainedMark: 22.56,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2022-01-17T15:34:54.8",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "3",
      RollNo: "1",
      idShift: 2,
      StudentName: "Amshu   Panthi",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10781,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10839,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 155,
      TotalAvgObtainedMark: 21.6,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "4",
      RollNo: "02",
      idShift: 2,
      StudentName: "Roshan  Chaulagain",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10782,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10840,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "5",
      RollNo: "06",
      idShift: 2,
      StudentName: "Mimosa  Singh",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10783,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10843,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "6",
      RollNo: "12",
      idShift: 2,
      StudentName: "Nisha  Maharjan",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10784,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10844,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "7",
      RollNo: "5",
      idShift: 2,
      StudentName: "Jiwana Shah Thakuri",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10785,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10845,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "8",
      RollNo: "07",
      idShift: 2,
      StudentName: "Isha   Poudel",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10786,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10846,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "9",
      RollNo: "13",
      idShift: 2,
      StudentName: "Shreeya  Magar",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10787,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10847,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "10",
      RollNo: "12",
      idShift: 2,
      StudentName: "Prashamsha  Khadki",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10788,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10848,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "11",
      RollNo: "15",
      idShift: 2,
      StudentName: "Aawaj  Thapa",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10789,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10849,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "12",
      RollNo: "11",
      idShift: 2,
      StudentName: "Shiva Shankar Thing",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10790,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10850,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "13",
      RollNo: "16",
      idShift: 2,
      StudentName: "Sweeta   Sharma",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10791,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10851,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "14",
      RollNo: "03",
      idShift: 2,
      StudentName: "Himal  Kunwar",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10792,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10852,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "15",
      RollNo: "05",
      idShift: 2,
      StudentName: "Sudina  Lohani",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10793,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10853,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "16",
      RollNo: "19",
      idShift: 2,
      StudentName: "Barsha  Rai",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10794,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10854,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "17",
      RollNo: "04",
      idShift: 2,
      StudentName: "Nisha   Tamang",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10795,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10855,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "18",
      RollNo: "3",
      idShift: 2,
      StudentName: "Prabin   Thapa",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10796,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10957,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "19",
      RollNo: "17",
      idShift: 2,
      StudentName: "Sulav   Devkota",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10797,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10961,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "20",
      RollNo: "10",
      idShift: 2,
      StudentName: "Rajesh   Giri",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10798,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10962,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "21",
      RollNo: "18",
      idShift: 2,
      StudentName: "Rekha  Mahat",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10799,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 10964,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-01T15:26:56.507",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "22",
      RollNo: "09",
      idShift: 2,
      StudentName: "Rekha  Karki",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 10800,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 12983,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2020-12-02T12:56:03.197",
      Updated_On: "2022-01-17T15:34:54.81",
    },
    {
      $id: "23",
      RollNo: "08",
      idShift: 2,
      StudentName: "Prashna   Bajgain",
      AcademicProgramName: "School",
      TotalMarkAnnualResult: 0,
      IDAcademicStudentExamResult: 41233,
      IDAcademicYearCalendar: 40100,
      IDHREmployee: 12987,
      TotalMark: 625,
      TotalPassMark: 250,
      TotalObtainedMark: 0,
      TotalAvgObtainedMark: 0,
      SecuredDivision: "Fail",
      DivisionComment: "FAILED",
      Comment: null,
      Status: "Publish",
      Created_On: "2022-01-17T15:27:26.967",
      Updated_On: "2022-01-17T15:34:54.81",
    },
  ],
  dbMarkModelLst: [
    {
      $id: "25",
      IDHREmployee: 10839,
      StudentExamStatus: 1,
      ObtainedMarks: 75,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "26",
      IDHREmployee: 10840,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "27",
      IDHREmployee: 10852,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "28",
      IDHREmployee: 10957,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "29",
      IDHREmployee: 10855,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "30",
      IDHREmployee: 10845,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "31",
      IDHREmployee: 10853,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "32",
      IDHREmployee: 10843,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "33",
      IDHREmployee: 10846,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "34",
      IDHREmployee: 12987,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "35",
      IDHREmployee: 12983,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "36",
      IDHREmployee: 10962,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "37",
      IDHREmployee: 10850,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "38",
      IDHREmployee: 10844,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "39",
      IDHREmployee: 10848,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "40",
      IDHREmployee: 10847,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "41",
      IDHREmployee: 10849,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "42",
      IDHREmployee: 10851,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "43",
      IDHREmployee: 10961,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "44",
      IDHREmployee: 10964,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "45",
      IDHREmployee: 10854,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "46",
      IDHREmployee: 10838,
      StudentExamStatus: 1,
      ObtainedMarks: 75,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1110,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "47",
      IDHREmployee: 10838,
      StudentExamStatus: 1,
      ObtainedMarks: 66,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 20,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "48",
      IDHREmployee: 10839,
      StudentExamStatus: 1,
      ObtainedMarks: 60,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 20,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "49",
      IDHREmployee: 10840,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "50",
      IDHREmployee: 10852,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "51",
      IDHREmployee: 10957,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "52",
      IDHREmployee: 10855,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "53",
      IDHREmployee: 10845,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "54",
      IDHREmployee: 10853,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "55",
      IDHREmployee: 10843,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "56",
      IDHREmployee: 10846,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "57",
      IDHREmployee: 12987,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "58",
      IDHREmployee: 12983,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "59",
      IDHREmployee: 10962,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "60",
      IDHREmployee: 10850,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "61",
      IDHREmployee: 10844,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "62",
      IDHREmployee: 10848,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Pass",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "63",
      IDHREmployee: 10847,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "64",
      IDHREmployee: 10849,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "65",
      IDHREmployee: 10851,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "66",
      IDHREmployee: 10961,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "67",
      IDHREmployee: 10964,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
    {
      $id: "68",
      IDHREmployee: 10854,
      StudentExamStatus: 1,
      ObtainedMarks: 0,
      FullMarks: 75,
      FullMarksPractical: 25,
      PassMarks: 30,
      Division: "Fail",
      IdAcademicSubject: 1109,
      ObtainedMarksPractical: 0,
      ObtainedMarksPreTerm: null,
      TotalPassMarksForAnnualResult: null,
      TotalObtainedMarksForAnnualResult: null,
      TotalFullMarksForAnnualResult: null,
      EventName: null,
    },
  ],
  ddlAcademicFacultySubjectLinkSubModel: [
    {
      $id: "69",
      IDAcademicFacultySubjectLink: 22141,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1109,
      Optional: false,
      Compulsory: true,
      SubjectName: "Science ",
      SubjectCode: "SCN-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "70",
      IDAcademicFacultySubjectLink: 22142,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1110,
      Optional: false,
      Compulsory: true,
      SubjectName: "English ",
      SubjectCode: "ENG-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "71",
      IDAcademicFacultySubjectLink: 22143,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1112,
      Optional: false,
      Compulsory: true,
      SubjectName: "Mathematics",
      SubjectCode: "C.MTH-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "72",
      IDAcademicFacultySubjectLink: 22144,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1113,
      Optional: false,
      Compulsory: true,
      SubjectName: "Social studies ",
      SubjectCode: "SOC-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "73",
      IDAcademicFacultySubjectLink: 22145,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1115,
      Optional: false,
      Compulsory: true,
      SubjectName: " Nepali ",
      SubjectCode: "NEP-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "74",
      IDAcademicFacultySubjectLink: 22146,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1116,
      Optional: false,
      Compulsory: true,
      SubjectName: "EPH  ",
      SubjectCode: "EPH-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "75",
      IDAcademicFacultySubjectLink: 22147,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1153,
      Optional: false,
      Compulsory: true,
      SubjectName: "Computer Science",
      SubjectCode: "CMPS-9",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
    {
      $id: "76",
      IDAcademicFacultySubjectLink: 22149,
      IDYearFacultyLink: 110,
      IdLevel: 0,
      IDAcademicSubject: 1160,
      Optional: false,
      Compulsory: true,
      SubjectName: "Opt. Math",
      SubjectCode: "optm",
      IsShowInLedger: true,
      IDAcademicExamSchedule: 0,
    },
  ],
  searchFilterModel: {
    $id: "77",
    ddlQuestionSection: null,
    ValidityDate: "0001-01-01T00:00:00",
    IdHREmployee: 0,
    idAdmissionFeeStructure: 0,
    Sem: 0,
    idAdmissionRegistration: 0,
    showAddButton: false,
    reportMode: null,
    reportDate: "0001-01-01T00:00:00",
    idAcademicYear: 52,
    idAssignment: 0,
    idStudent: 0,
    idTeacher: 0,
    idFacultyProgramLink: 6,
    idAcademicExamSchedule: 0,
    idAcademicYearCalendar: 40100,
    idSubject: 0,
    idTeacherFacultySubjectMappingHeader: 0,
    level: 13,
    idShift: 2,
    idActivityType: 0,
    idActivityCount: 0,
    section: null,
    classSection: 1,
    npMonth: 0,
    npYear: 52,
    title: null,
    yr: 0,
    idOnlineExamSet: 0,
    mth: 0,
    fromDate: "0001-01-01T00:00:00",
    currentDate: "0001-01-01T00:00:00",
    toDate: "0001-01-01T00:00:00",
    fiscalYear: null,
    ddlAcademicYearCalendar: [
      {
        $id: "78",
        Key: 40100,
        Value: "FIRST TERM EXAMINATION",
      },
    ],
    ddlAcademicExamSchedule: null,
    ddlAcademicYear: null,
    ddlAcademicYearPrimitive: null,
    ddlTeacherFacultySubjectMappingHeader: null,
    ddlAssignment: null,
    ddlStudent: null,
    ddlTeacher: null,
    ddlActivityType: null,
    ddlAcademicShift: [
      {
        $id: "79",
        Key: 2,
        Value: "Morning",
      },
    ],
    ddlFiscalYear: null,
    ddlExamSet: null,
    ddlSubject: null,
    ddlYear: null,
    ddlMonth: null,
    ddlnpYear: null,
    ddlnpMonth: null,
    ddlFacultyProgramLink: [
      {
        $id: "80",
        Key: 6,
        Value: "School/Secondary",
      },
    ],
    ddlLevel: null,
    ddlLevelPrimitive: null,
    ddlSection: null,
    ddlStudentLevel: null,
    ddlStudentExamStatus: null,
    ddlActivityCount: null,
    idClass: 0,
    ddlClass: null,
    nextClass: 0,
    dbModel: null,
    RegistrationKey: null,
    ImageFullPath: null,
    feeCollectionModel: null,
    studentDueModel: null,
    company: 0,
    ddlCompany: null,
    searchString: "",
    baseUrl: null,
    baseUrlExtended: null,
    searchParamCode: null,
    idSessionUser: 0,
    pidRefForEdit: null,
    idRole: 0,
    ddlRole: null,
    studentLedgerModel: null,
    StartDate: "0001-01-01T00:00:00",
    EndDate: "0001-01-01T00:00:00",
    ddlAccountFiscalYear: null,
    IDFiscalYear: 0,
  },
  ExamHeldDate: "2020-11-30T00:00:00",
  ExamEndDate: "2020-11-30T00:00:00",
  ResultPublishDate: "2020-12-01T00:00:00",
  ddlStudent: null,
  dbModelRankLst: [
    {
      $id: "81",
      Key: 10838,
      Value: 1,
    },
    {
      $id: "82",
      Key: 10839,
      Value: 2,
    },
  ],
  Prefix: "th",
  dbModelResultLst: [
    {
      $id: "83",
      Identifier: 161,
      Key: 10838,
      Value: "Pass",
    },
    {
      $id: "84",
      Identifier: 155,
      Key: 10839,
      Value: "Pass",
    },
    {
      $id: "85",
      Identifier: 0,
      Key: 10840,
      Value: "Fail",
    },
    {
      $id: "86",
      Identifier: 0,
      Key: 10843,
      Value: "Fail",
    },
    {
      $id: "87",
      Identifier: 0,
      Key: 10844,
      Value: "Fail",
    },
    {
      $id: "88",
      Identifier: 0,
      Key: 10845,
      Value: "Fail",
    },
    {
      $id: "89",
      Identifier: 0,
      Key: 10846,
      Value: "Fail",
    },
    {
      $id: "90",
      Identifier: 0,
      Key: 10847,
      Value: "Fail",
    },
    {
      $id: "91",
      Identifier: 0,
      Key: 10848,
      Value: "Fail",
    },
    {
      $id: "92",
      Identifier: 0,
      Key: 10849,
      Value: "Fail",
    },
    {
      $id: "93",
      Identifier: 0,
      Key: 10850,
      Value: "Fail",
    },
    {
      $id: "94",
      Identifier: 0,
      Key: 10851,
      Value: "Fail",
    },
    {
      $id: "95",
      Identifier: 0,
      Key: 10852,
      Value: "Fail",
    },
    {
      $id: "96",
      Identifier: 0,
      Key: 10853,
      Value: "Fail",
    },
    {
      $id: "97",
      Identifier: 0,
      Key: 10854,
      Value: "Fail",
    },
    {
      $id: "98",
      Identifier: 0,
      Key: 10855,
      Value: "Fail",
    },
    {
      $id: "99",
      Identifier: 0,
      Key: 10957,
      Value: "Fail",
    },
    {
      $id: "100",
      Identifier: 0,
      Key: 10961,
      Value: "Fail",
    },
    {
      $id: "101",
      Identifier: 0,
      Key: 10962,
      Value: "Fail",
    },
    {
      $id: "102",
      Identifier: 0,
      Key: 10964,
      Value: "Fail",
    },
    {
      $id: "103",
      Identifier: 0,
      Key: 12983,
      Value: "Fail",
    },
    {
      $id: "104",
      Identifier: 0,
      Key: 12987,
      Value: "Fail",
    },
  ],
  messageModel: {
    $id: "105",
    title: "List ExamResult",
    area: "Examination",
    controller: "ExamResult",
    action: "Index",
  },
};
