export const GET_ALL_ANNOUNCEMENT_REQUEST = "GET_ALL_ANNOUNCEMENT_REQUEST";
export const GET_ALL_ANNOUNCEMENT_SUCCESS = "GET_ALL_ANNOUNCEMENT_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_FAIL = "GET_ALL_ANNOUNCEMENT_FAIL";
export const GET_ALL_ANNOUNCEMENT_RESET = "GET_ALL_ANNOUNCEMENT_RESET";

export const GET_LIST_ANNOUNCEMENT_REQUEST = "GET_LIST_ANNOUNCEMENT_REQUEST";
export const GET_LIST_ANNOUNCEMENT_SUCCESS = "GET_LIST_ANNOUNCEMENT_SUCCESS";
export const GET_LIST_ANNOUNCEMENT_FAIL = "GET_LIST_ANNOUNCEMENT_FAIL";
export const GET_LIST_ANNOUNCEMENT_RESET = "GET_LIST_ANNOUNCEMENT_RESET";

export const ANNOUNCEMENT_FCM_REQUEST = "ANNOUNCEMENT_FCM_REQUEST";
export const ANNOUNCEMENT_FCM_SUCCESS = "ANNOUNCEMENT_FCM_SUCCESS";
export const ANNOUNCEMENT_FCM_FAIL = "ANNOUNCEMENT_FCM_FAIL";
export const ANNOUNCEMENT_FCM_RESET = "ANNOUNCEMENT_FCM_RESET";

export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_CREATE_SUCCESS = "ANNOUNCEMENT_CREATE_SUCCESS";
export const ANNOUNCEMENT_CREATE_FAIL = "ANNOUNCEMENT_CREATE_FAIL";
export const ANNOUNCEMENT_CREATE_RESET = "ANNOUNCEMENT_CREATE_RESET";

export const GET_SINGLE_ANNOUNCEMENT_REQUEST =
  "GET_SINGLE_ANNOUNCEMENT_REQUEST";
export const GET_SINGLE_ANNOUNCEMENT_SUCCESS =
  "GET_SINGLE_ANNOUNCEMENT_SUCCESS";
export const GET_SINGLE_ANNOUNCEMENT_FAIL = "GET_SINGLE_ANNOUNCEMENT_FAIL";
export const GET_SINGLE_ANNOUNCEMENT_RESET = "GET_SINGLE_ANNOUNCEMENT_RESET";

export const UPDATE_SINGLE_ANNOUNCEMENT_REQUEST =
  "UPDATE_SINGLE_ANNOUNCEMENT_REQUEST";
export const UPDATE_SINGLE_ANNOUNCEMENT_SUCCESS =
  "UPDATE_SINGLE_ANNOUNCEMENT_SUCCESS";
export const UPDATE_SINGLE_ANNOUNCEMENT_FAIL =
  "UPDATE_SINGLE_ANNOUNCEMENT_FAIL";
export const UPDATE_SINGLE_ANNOUNCEMENT_RESET =
  "UPDATE_SINGLE_ANNOUNCEMENT_RESET";
