export const GET_INITIAL_ADMIT_CARD_DATA_REQUEST =
  "GET_INITIAL_ADMIT_CARD_DATA_REQUEST";
export const GET_INITIAL_ADMIT_CARD_DATA_SUCCESS =
  "GET_INITIAL_ADMIT_CARD_DATA_SUCCESS";
export const GET_INITIAL_ADMIT_CARD_DATA_FAIL =
  "GET_INITIAL_ADMIT_CARD_DATA_FAIL";

export const GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_REQUEST =
  "GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_REQUEST";
export const GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_SUCCESS =
  "GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_SUCCESS";
export const GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_FAIL =
  "GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_FAIL";
export const GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_RESET =
  "GET_ACTIVE_STUDENTS_FOR_ADMIT_CARD_RESET";

export const SEARCH_STUDENTS_FOR_ADMIT_CARD_REQUEST =
  "SEARCH_STUDENTS_FOR_ADMIT_CARD_REQUEST";
export const SEARCH_STUDENTS_FOR_ADMIT_CARD_SUCCESS =
  "SEARCH_STUDENTS_FOR_ADMIT_CARD_SUCCESS";
export const SEARCH_STUDENTS_FOR_ADMIT_CARD_FAIL =
  "SEARCH_STUDENTS_FOR_ADMIT_CARD_FAIL";
  export const SEARCH_STUDENTS_FOR_ADMIT_CARD_RESET =
  "SEARCH_STUDENTS_FOR_ADMIT_CARD_RESET";

export const PRINT_STUDENTS_ADMIT_CARD_REQUEST =
  "PRINT_STUDENTS_ADMIT_CARD_REQUEST";
export const PRINT_STUDENTS_ADMIT_CARD_SUCCESS =
  "PRINT_STUDENTS_ADMIT_CARD_SUCCESS";
export const PRINT_STUDENTS_ADMIT_CARD_FAIL = "PRINT_STUDENTS_ADMIT_CARD_FAIL";
