export const GET_ALL_ASSIGN_FACULTY_SUBJECT_REQUEST =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_REQUEST";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_SUCCESS =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_SUCCESS";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_FAIL =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_FAIL";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_RESET =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_RESET";

export const GET_LIST_ASSIGN_FACULTY_SUBJECT_REQUEST =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_REQUEST";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_SUCCESS =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_SUCCESS";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_FAIL =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_FAIL";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_RESET =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_RESET";

export const ASSIGN_FACULTY_SUBJECT_GET_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_GET_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_GET_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_GET_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_GET_FAIL =
  "ASSIGN_FACULTY_SUBJECT_GET_FAIL";
export const ASSIGN_FACULTY_SUBJECT_GET_RESET =
  "ASSIGN_FACULTY_SUBJECT_GET_RESET";
