export const GET_ALL_ASSIGN_FACULTY_SUBJECT_REQUEST =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_REQUEST";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_SUCCESS =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_SUCCESS";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_FAIL =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_FAIL";
export const GET_ALL_ASSIGN_FACULTY_SUBJECT_RESET =
  "GET_ALL_ASSIGN_FACULTY_SUBJECT_RESET";

export const GET_LIST_ASSIGN_FACULTY_SUBJECT_REQUEST =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_REQUEST";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_SUCCESS =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_SUCCESS";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_FAIL =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_FAIL";
export const GET_LIST_ASSIGN_FACULTY_SUBJECT_RESET =
  "GET_LIST_ASSIGN_FACULTY_SUBJECT_RESET";

export const ASSIGN_FACULTY_SUBJECT_GET_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_GET_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_GET_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_GET_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_GET_FAIL =
  "ASSIGN_FACULTY_SUBJECT_GET_FAIL";
export const ASSIGN_FACULTY_SUBJECT_GET_RESET =
  "ASSIGN_FACULTY_SUBJECT_GET_RESET";

export const ASSIGN_FACULTY_SUBJECT_POST_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_POST_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_POST_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_POST_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_POST_FAIL =
  "ASSIGN_FACULTY_SUBJECT_POST_FAIL";
export const ASSIGN_FACULTY_SUBJECT_POST_RESET =
  "ASSIGN_FACULTY_SUBJECT_POST_RESET";

export const GET_SINGLE_ASSIGN_FACULTY_SUBJECT_REQUEST =
  "GET_SINGLE_ASSIGN_FACULTY_SUBJECT_REQUEST";
export const GET_SINGLE_ASSIGN_FACULTY_SUBJECT_SUCCESS =
  "GET_SINGLE_ASSIGN_FACULTY_SUBJECT_SUCCESS";
export const GET_SINGLE_ASSIGN_FACULTY_SUBJECT_FAIL =
  "GET_SINGLE_ASSIGN_FACULTY_SUBJECT_FAIL";
export const GET_SINGLE_ASSIGN_FACULTY_SUBJECT_RESET =
  "GET_SINGLE_ASSIGN_FACULTY_SUBJECT_RESET";

export const ASSIGN_FACULTY_SUBJECT_EDIT_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_EDIT_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_EDIT_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_EDIT_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_EDIT_FAIL =
  "ASSIGN_FACULTY_SUBJECT_EDIT_FAIL";
export const ASSIGN_FACULTY_SUBJECT_EDIT_RESET =
  "ASSIGN_FACULTY_SUBJECT_EDIT_RESET";

export const ASSIGN_FACULTY_SUBJECT_EDIT_POST_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_EDIT_POST_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_EDIT_POST_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_EDIT_POST_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_EDIT_POST_FAIL =
  "ASSIGN_FACULTY_SUBJECT_EDIT_POST_FAIL";
export const ASSIGN_FACULTY_SUBJECT_EDIT_POST_RESET =
  "ASSIGN_FACULTY_SUBJECT_EDIT_POST_RESET";

export const ASSIGN_FACULTY_SUBJECT_GENERATE_REQUEST =
  "ASSIGN_FACULTY_SUBJECT_GENERATE_REQUEST";
export const ASSIGN_FACULTY_SUBJECT_GENERATE_SUCCESS =
  "ASSIGN_FACULTY_SUBJECT_GENERATE_SUCCESS";
export const ASSIGN_FACULTY_SUBJECT_GENERATE_FAIL =
  "ASSIGN_FACULTY_SUBJECT_GENERATE_FAIL";
export const ASSIGN_FACULTY_SUBJECT_GENERATE_RESET =
  "ASSIGN_FACULTY_SUBJECT_GENERATE_RESET";
