export const GET_INITIAL_STUDENT_ID_CARD_DATA_REQUEST =
  "GET_INITIAL_STUDENT_ID_CARD_DATA_REQUEST";
export const GET_INITIAL_STUDENT_ID_CARD_DATA_SUCCESS =
  "GET_INITIAL_STUDENT_ID_CARD_DATA_SUCCESS";
export const GET_INITIAL_STUDENT_ID_CARD_DATA_FAIL =
  "GET_INITIAL_STUDENT_ID_CARD_DATA_FAIL";
export const GET_INITIAL_STUDENT_ID_CARD_DATA_RESET =
  "GET_INITIAL_STUDENT_ID_CARD_DATA_FAIL";

export const GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_REQUEST =
  "GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_REQUEST";
export const GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_SUCCESS =
  "GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_SUCCESS";
export const GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_FAIL =
  "GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_FAIL";
export const GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_RESET =
  "GET_ACTIVE_STUDENTS_FOR_STUDENT_ID_CARD_RESET";

  export const GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_REQUEST =
  "GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_REQUEST";
export const GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_SUCCESS =
  "GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_SUCCESS";
export const GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_FAIL =
  "GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_FAIL";
export const GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_RESET =
  "GET_PRINT_BULK_STUDENTS_FOR_STUDENT_ID_CARD_RESET";
