export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_REQUEST =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_REQUEST";
export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_SUCCESS =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_SUCCESS";
export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_FAIL =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_FAIL";
export const GET_ALL_EMPLOYEE_CATEGORY_ROLE_RESET =
  "GET_ALL_EMPLOYEE_CATEGORY_ROLE_RESET";

export const EMPLOYEE_CATEGORY_ROLE_CREATE_REQUEST =
  "EMPLOYEE_CATEGORY_ROLE_CREATE_REQUEST";
export const EMPLOYEE_CATEGORY_ROLE_CREATE_SUCCESS =
  "EMPLOYEE_CATEGORY_ROLE_CREATE_SUCCESS";
export const EMPLOYEE_CATEGORY_ROLE_CREATE_FAIL =
  "EMPLOYEE_CATEGORY_ROLE_CREATE_FAIL";
export const EMPLOYEE_CATEGORY_ROLE_CREATE_RESET =
  "EMPLOYEE_CATEGORY_ROLE_CREATE_RESET";

export const GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_REQUEST =
  "GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_REQUEST";
export const GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_SUCCESS =
  "GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_FAIL =
  "GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_FAIL";
export const GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_RESET =
  "GET_SINGLE_EMPLOYEE_CATEGORY_ROLE_RESET";

export const UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_REQUEST =
  "UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_REQUEST";
export const UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_SUCCESS =
  "UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_SUCCESS";
export const UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_FAIL =
  "UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_FAIL";
export const UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_RESET =
  "UPDATE_SINGLE_EMPLOYEE_CATEGORY_ROLE_RESET";

  export const DELETE_EMPLOYEE_CATEGORY_ROLE_REQUEST =
  "DELETE_EMPLOYEE_CATEGORY_ROLE_REQUEST";
export const DELETE_EMPLOYEE_CATEGORY_ROLE_SUCCESS =
  "DELETE_EMPLOYEE_CATEGORY_ROLE_SUCCESS";
export const DELETE_EMPLOYEE_CATEGORY_ROLE_FAIL =
  "DELETE_EMPLOYEE_CATEGORY_ROLE_FAIL";
export const DELETE_EMPLOYEE_CATEGORY_ROLE_RESET =
  "DELETE_EMPLOYEE_CATEGORY_ROLE_RESET";
