export const GET_COUNTER_CONFIG_INITIAL_DATA_REQUEST =
  "GET_COUNTER_CONFIG_INITIAL_DATA_REQUEST";
export const GET_COUNTER_CONFIG_INITIAL_DATA_SUCCESS =
  "GET_COUNTER_CONFIG_INITIAL_DATA_SUCCESS";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FAIL =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FAIL";
export const GET_COUNTER_CONFIG_INITIAL_DATA_RESET =
  "GET_COUNTER_CONFIG_INITIAL_DATA_RESET";

export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_REQUEST =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_REQUEST";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_SUCCESS =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_SUCCESS";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_FAIL =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_FAIL";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_RESET =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_CREATE_RESET";

export const COUNTER_CONFIG_CREATE_REQUEST = "COUNTER_CONFIG_CREATE_REQUEST";
export const COUNTER_CONFIG_CREATE_SUCCESS = "COUNTER_CONFIG_CREATE_SUCCESS";
export const COUNTER_CONFIG_CREATE_FAIL = "COUNTER_CONFIG_CREATE_FAIL";
export const COUNTER_CONFIG_CREATE_RESET = "COUNTER_CONFIG_CREATE_RESET";

export const GET_COUNTER_CONFIG_LIST_REQUEST =
  "GET_COUNTER_CONFIG_LIST_REQUEST";
export const GET_COUNTER_CONFIG_LIST_SUCCESS =
  "GET_COUNTER_CONFIG_LIST_SUCCESS";
export const GET_COUNTER_CONFIG_LIST_FAIL = "GET_COUNTER_CONFIG_LIST_FAIL";
export const GET_COUNTER_CONFIG_LIST_RESET = "GET_COUNTER_CONFIG_LIST_RESET";

export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_REQUEST =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_REQUEST";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_SUCCESS =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_SUCCESS";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_FAIL =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_FAIL";
export const GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_RESET =
  "GET_COUNTER_CONFIG_INITIAL_DATA_FOR_EDIT_RESET";

export const COUNTER_CONFIG_EDIT_REQUEST = "COUNTER_CONFIG_EDIT_REQUEST";
export const COUNTER_CONFIG_EDIT_SUCCESS = "COUNTER_CONFIG_EDIT_SUCCESS";
export const COUNTER_CONFIG_EDIT_FAIL = "COUNTER_CONFIG_EDIT_FAIL";
export const COUNTER_CONFIG_EDIT_RESET = "COUNTER_CONFIG_EDIT_RESET";
