export const GET_ALL_SYLLABUS_REQUEST = "GET_ALL_SYLLABUS_REQUEST";
export const GET_ALL_SYLLABUS_SUCCESS = "GET_ALL_SYLLABUS_SUCCESS";
export const GET_ALL_SYLLABUS_FAIL = "GET_ALL_SYLLABUS_FAIL";
export const GET_ALL_SYLLABUS_RESET = "GET_ALL_SYLLABUS_RESET";

export const GET_LIST_SYLLABUS_REQUEST = "GET_LIST_SYLLABUS_REQUEST";
export const GET_LIST_SYLLABUS_SUCCESS = "GET_LIST_SYLLABUS_SUCCESS";
export const GET_LIST_SYLLABUS_FAIL = "GET_LIST_SYLLABUS_FAIL";
export const GET_LIST_SYLLABUS_RESET = "GET_LIST_SYLLABUS_RESET";


export const GET_SINGLE_TO_EDIT_SYLLABUS_REQUEST = "GET_SINGLE_TO_EDIT_SYLLABUS_REQUEST";
export const GET_SINGLE_TO_EDIT_SYLLABUS_SUCCESS = "GET_SINGLE_TO_EDIT_SYLLABUS_SUCCESS";
export const GET_SINGLE_TO_EDIT_SYLLABUS_FAIL = "GET_SINGLE_TO_EDIT_SYLLABUS_FAIL";
export const GET_SINGLE_TO_EDIT_SYLLABUS_RESET = "GET_SINGLE_TO_EDIT_SYLLABUS_RESET";

export const PUT_SYLLABUS_REQUEST = "PUT_SYLLABUS_REQUEST";
export const PUT_SYLLABUS_SUCCESS = "PUT_SYLLABUS_SUCCESS";
export const PUT_SYLLABUS_FAIL = "PUT_SYLLABUS_FAIL";
export const PUT_SYLLABUS_RESET = "PUT_SYLLABUS_RESET";

