export const GET_ALL_TRAINING_REQUEST = 'GET_ALL_TRAINING_REQUEST';
export const GET_ALL_TRAINING_SUCCESS = 'GET_ALL_TRAINING_SUCCESS';
export const GET_ALL_TRAINING_FAIL = 'GET_ALL_TRAINING_FAIL';
export const GET_ALL_TRAINING_RESET = 'GET_ALL_TRAINING_RESET';