export const GET_ALL_CLASS_NOTIFICATION_REQUEST = "GET_ALL_CLASS_NOTIFICATION_REQUEST";
export const GET_ALL_CLASS_NOTIFICATION_SUCCESS = "GET_ALL_CLASS_NOTIFICATION_SUCCESS";
export const GET_ALL_CLASS_NOTIFICATION_FAIL = "GET_ALL_CLASS_NOTIFICATION_FAIL";
export const GET_ALL_CLASS_NOTIFICATION_RESET = "GET_ALL_CLASS_NOTIFICATION_RESET";

export const GET_LIST_CLASS_NOTIFICATION_REQUEST = "GET_LIST_CLASS_NOTIFICATION_REQUEST";
export const GET_LIST_CLASS_NOTIFICATION_SUCCESS = "GET_LIST_CLASS_NOTIFICATION_SUCCESS";
export const GET_LIST_CLASS_NOTIFICATION_FAIL = "GET_LIST_CLASS_NOTIFICATION_FAIL";
export const GET_LIST_CLASS_NOTIFICATION_RESET = "GET_LIST_CLASS_NOTIFICATION_RESET";

export const GET_BULK_CLASS_NOTIFICATION_REQUEST = "GET_BULK_CLASS_NOTIFICATION_REQUEST";
export const GET_BULK_CLASS_NOTIFICATION_SUCCESS = "GET_BULK_CLASS_NOTIFICATION_SUCCESS";
export const GET_BULK_CLASS_NOTIFICATION_FAIL = "GET_BULK_CLASS_NOTIFICATION_FAIL";
export const GET_BULK_CLASS_NOTIFICATION_RESET = "GET_BULK_CLASS_NOTIFICATION_RESET";

export const POST_CLASS_NOTIFICATION_REQUEST = "POST_CLASS_NOTIFICATION_REQUEST";
export const POST_CLASS_NOTIFICATION_SUCCESS = "POST_CLASS_NOTIFICATION_SUCCESS";
export const POST_CLASS_NOTIFICATION_FAIL = "POST_CLASS_NOTIFICATION_FAIL";
export const POST_CLASS_NOTIFICATION_RESET = "POST_CLASS_NOTIFICATION_RESET";