export const GET_NOTIFICATION_EMPLOYEELIST_SEARCH_REQUEST =
  "GET_NOTIFICATION_EMPLOYEELIST_SEARCH_REQUEST";
export const GET_NOTIFICATION_EMPLOYEELIST_SEARCH_SUCCESS =
  "GET_NOTIFICATION_EMPLOYEELIST_SEARCH_SUCCESS";
export const GET_NOTIFICATION_EMPLOYEELIST_SEARCH_FAIL = "GET_NOTIFICATION_EMPLOYEELIST_SEARCH_FAIL";
export const GET_NOTIFICATION_EMPLOYEELIST_SEARCH_RESET = "GET_NOTIFICATION_EMPLOYEELIST_SEARCH_RESET";


export const GET_NOTIFICATION_FCM_TOKEN_REQUEST =
  "GET_NOTIFICATION_FCM_TOKEN_REQUEST";
export const GET_NOTIFICATION_FCM_TOKEN_SUCCESS =
  "GET_NOTIFICATION_FCM_TOKEN_SUCCESS";
export const GET_NOTIFICATION_FCM_TOKEN_FAIL = "GET_NOTIFICATION_FCM_TOKEN_FAIL";
export const GET_NOTIFICATION_FCM_TOKEN_RESET = "GET_NOTIFICATION_FCM_TOKEN_RESET";


export const POST_NOTIFICATION_FCM_TOKEN_REQUEST =
  "POST_NOTIFICATION_FCM_TOKEN_REQUEST";
export const POST_NOTIFICATION_FCM_TOKEN_SUCCESS =
  "POST_NOTIFICATION_FCM_TOKEN_SUCCESS";
export const POST_NOTIFICATION_FCM_TOKEN_FAIL = "POST_NOTIFICATION_FCM_TOKEN_FAIL";
export const POST_NOTIFICATION_FCM_TOKEN_RESET = "POST_NOTIFICATION_FCM_TOKEN_RESET";
