export const GET_ALL_SCHOOL_SETTINGS_REQUEST =
  "GET_ALL_SCHOOL_SETTINGS_REQUEST";
export const GET_ALL_SCHOOL_SETTINGS_SUCCESS =
  "GET_ALL_SCHOOL_SETTINGS_SUCCESS";
export const GET_ALL_SCHOOL_SETTINGS_FAIL = "GET_ALL_SCHOOL_SETTINGS_FAIL";
export const GET_ALL_SCHOOL_SETTINGS_RESET = "GET_ALL_SCHOOL_SETTINGS_RESET";

export const SCHOOL_SETTINGS_CREATE_REQUEST = "SCHOOL_SETTINGS_CREATE_REQUEST";
export const SCHOOL_SETTINGS_CREATE_SUCCESS = "SCHOOL_SETTINGS_CREATE_SUCCESS";
export const SCHOOL_SETTINGS_CREATE_FAIL = "SCHOOL_SETTINGS_CREATE_FAIL";
export const SCHOOL_SETTINGS_CREATE_RESET = "SCHOOL_SETTINGS_CREATE_RESET";

export const GET_SINGLE_SCHOOL_SETTINGS_REQUEST =
  "GET_SINGLE_SCHOOL_SETTINGS_REQUEST";
export const GET_SINGLE_SCHOOL_SETTINGS_SUCCESS =
  "GET_SINGLE_SCHOOL_SETTINGS_SUCCESS";
export const GET_SINGLE_SCHOOL_SETTINGS_FAIL =
  "GET_SINGLE_SCHOOL_SETTINGS_FAIL";
export const GET_SINGLE_SCHOOL_SETTINGS_RESET =
  "GET_SINGLE_SCHOOL_SETTINGS_RESET";

export const UPDATE_SINGLE_SCHOOL_SETTINGS_REQUEST =
  "UPDATE_SINGLE_SCHOOL_SETTINGS_REQUEST";
export const UPDATE_SINGLE_SCHOOL_SETTINGS_SUCCESS =
  "UPDATE_SINGLE_SCHOOL_SETTINGS_SUCCESS";
export const UPDATE_SINGLE_SCHOOL_SETTINGS_FAIL =
  "UPDATE_SINGLE_SCHOOL_SETTINGS_FAIL";
export const UPDATE_SINGLE_SCHOOL_SETTINGS_RESET =
  "UPDATE_SINGLE_SCHOOL_SETTINGS_RESET";
