export const GET_ALL_SCHOOL_BOARD_REQUEST = "GET_ALL_SCHOOL_BOARD_REQUEST";
export const GET_ALL_SCHOOL_BOARD_SUCCESS = "GET_ALL_SCHOOL_BOARD_SUCCESS";
export const GET_ALL_SCHOOL_BOARD_FAIL = "GET_ALL_SCHOOL_BOARD_FAIL";
export const GET_ALL_SCHOOL_BOARD_RESET = "GET_ALL_SCHOOL_BOARD_RESET";

export const SCHOOL_BOARD_CREATE_REQUEST = "SCHOOL_BOARD_CREATE_REQUEST";
export const SCHOOL_BOARD_CREATE_SUCCESS = "SCHOOL_BOARD_CREATE_SUCCESS";
export const SCHOOL_BOARD_CREATE_FAIL = "SCHOOL_BOARD_CREATE_FAIL";
export const SCHOOL_BOARD_CREATE_RESET = "SCHOOL_BOARD_CREATE_RESET";

export const GET_SINGLE_SCHOOL_BOARD_REQUEST =
  "GET_SINGLE_SCHOOL_BOARD_REQUEST";
export const GET_SINGLE_SCHOOL_BOARD_SUCCESS =
  "GET_SINGLE_SCHOOL_BOARD_SUCCESS";
export const GET_SINGLE_SCHOOL_BOARD_FAIL = "GET_SINGLE_SCHOOL_BOARD_FAIL";
export const GET_SINGLE_SCHOOL_BOARD_RESET = "GET_SINGLE_SCHOOL_BOARD_RESET";

export const UPDATE_SINGLE_SCHOOL_BOARD_REQUEST =
  "UPDATE_SINGLE_SCHOOL_BOARD_REQUEST";
export const UPDATE_SINGLE_SCHOOL_BOARD_SUCCESS =
  "UPDATE_SINGLE_SCHOOL_BOARD_SUCCESS";
export const UPDATE_SINGLE_SCHOOL_BOARD_FAIL =
  "UPDATE_SINGLE_SCHOOL_BOARD_FAIL";
export const UPDATE_SINGLE_SCHOOL_BOARD_RESET =
  "UPDATE_SINGLE_SCHOOL_BOARD_RESET";
