export const GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL";
export const GET_ALL_EMPLOYEE_RESET = "GET_ALL_EMPLOYEE_RESET";

export const GET_ALL_EMPLOYEE_CREATE_REQUEST =
  "GET_ALL_EMPLOYEE_CREATE_REQUEST";
export const GET_ALL_EMPLOYEE_CREATE_SUCCESS =
  "GET_ALL_EMPLOYEE_CREATE_SUCCESS";
export const GET_ALL_EMPLOYEE_CREATE_FAIL = "GET_ALL_EMPLOYEE_CREATE_FAIL";
export const GET_ALL_EMPLOYEE_CREATE_RESET = "GET_ALL_EMPLOYEE_CREATE_RESET";

export const EMPLOYEE_CREATE_REQUEST = "EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL = "EMPLOYEE_CREATE_FAIL";
export const EMPLOYEE_CREATE_RESET = "EMPLOYEE_CREATE_RESET";

export const GET_SINGLE_EMPLOYEE_REQUEST = "GET_SINGLE_EMPLOYEE_REQUEST";
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_FAIL = "GET_SINGLE_EMPLOYEE_FAIL";
export const GET_SINGLE_EMPLOYEE_RESET = "GET_SINGLE_EMPLOYEE_RESET";

export const UPDATE_SINGLE_EMPLOYEE_REQUEST = "UPDATE_SINGLE_EMPLOYEE_REQUEST";
export const UPDATE_SINGLE_EMPLOYEE_SUCCESS = "UPDATE_SINGLE_EMPLOYEE_SUCCESS";
export const UPDATE_SINGLE_EMPLOYEE_FAIL = "UPDATE_SINGLE_EMPLOYEE_FAIL";
export const UPDATE_SINGLE_EMPLOYEE_RESET = "UPDATE_SINGLE_EMPLOYEE_RESET";

export const GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_REQUEST =
  "GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_REQUEST";
export const GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_SUCCESS =
  "GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_SUCCESS";
export const GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_FAIL =
  "GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_FAIL";
export const GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_RESET =
  "GET_RESETPASSWORD_DATA_SINGLE_EMPLOYEE_RESET";

export const RESETPASSWORD_FOR_SINGLE_EMPLOYEE_REQUEST =
  "RESETPASSWORD_FOR_SINGLE_EMPLOYEE_REQUEST";
export const RESETPASSWORD_FOR_SINGLE_EMPLOYEE_SUCCESS =
  "RESETPASSWORD_FOR_SINGLE_EMPLOYEE_SUCCESS";
export const RESETPASSWORD_FOR_SINGLE_EMPLOYEE_FAIL =
  "RESETPASSWORD_FOR_SINGLE_EMPLOYEE_FAIL";
export const RESETPASSWORD_FOR_SINGLE_EMPLOYEE_RESET =
  "RESETPASSWORD_FOR_SINGLE_EMPLOYEE_RESET";
