export const GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL";

export const GET_ALL_EMPLOYEE_CREATE_REQUEST =
  "GET_ALL_EMPLOYEE_CREATE_REQUEST";
export const GET_ALL_EMPLOYEE_CREATE_SUCCESS =
  "GET_ALL_EMPLOYEE_CREATE_SUCCESS";
export const GET_ALL_EMPLOYEE_CREATE_FAIL = "GET_ALL_EMPLOYEE_CREATE_FAIL";

export const EMPLOYEE_CREATE_REQUEST = "EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL = "EMPLOYEE_CREATE_FAIL";
export const EMPLOYEE_CREATE_RESET = "EMPLOYEE_CREATE_RESET";
