export const GET_ALL_SCHOOL_SETTINGS_REQUEST =
  "GET_ALL_SCHOOL_SETTINGS_REQUEST";
export const GET_ALL_SCHOOL_SETTINGS_SUCCESS =
  "GET_ALL_SCHOOL_SETTINGS_SUCCESS";
export const GET_ALL_SCHOOL_SETTINGS_FAIL = "GET_ALL_SCHOOL_SETTINGS_FAIL";
